### ISSUE TITLE
How to name a file with persisted entity id ?

### ISSUE THREAD

**Issue by Kwadz** [1up-lab/OneupUploaderBundle#123]
Hello,

I am wondering how to to upload a file after it is stored in database. However, maybe there is an other way to name the file with the id of the persisted entity ?

And to do this, is it possible to make the database operation and the moving of the file become atomic, as presented in [the Synfony2 documentation](http://symfony.com/doc/2.3/cookbook/doctrine/file_uploads.html#using-lifecycle-callbacks) ?

Many thanks.

**Comment by bytehead** [comment]
See #250.
