### ISSUE TITLE
Handling many to many relationship, how to?

### ISSUE THREAD

**Issue by reypm** [1up-lab/OneupUploaderBundle#126]
Even after read the docs I'm still not clear at all in how to handle upload at entity level. For example I have a relationship `n:m` where `many products can have many pictures` so I have a `ProductHasImages` entity where I should store the uploaded image ID and the related product ID, where, after upload multiple images, I should handle this? Any advice?

**Comment by olivier1208** [comment]
How do you fetch the 'productId' ??
On this line
` $productId = $request->get('product');`
Thanks

**Comment by sheeep** [comment]
> How do you fetch the 'productId' ??

You need to include it in your request.

https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_logic.md#use-custom-input-data

**Comment by zearg** [comment]
Is this secure to let user edit the GalleryId via script in frontend ?
-> Maybe we have to check gallery owner in "onUpload" Listener

**Comment by sheeep** [comment]
> Is this secure to let user edit the GalleryId via script in frontend ?

No user data should ever be trusted. But you need to check that yourself :)
