### ISSUE TITLE
Is there a way to load existing files?

### ISSUE THREAD

**Issue by coolmaplelin** [1up-lab/OneupUploaderBundle#130]
Hi

I am using blueimp jquery upload in oneupuploaderbundle. I was wondering if there is a way to load existing files like the basic plus ui in http://blueimp.github.io/jQuery-File-Upload/? 

Say I have an interface to upload the files. After I upload the files and gets into the interface again all the existing files will be listed. 

Or is this something we need to write by our own?

**Comment by slimittn** [comment]
Is there an exemple of how to create own logic to list existing files ? Even for Fine Uploader ?

**Comment by JHGitty** [comment]
You need to create a 'session' endpoint which returns all current files.
More info: http://docs.fineuploader.com/branch/develop/features/session.html
