### ISSUE TITLE
Files are not uploaded and UploadListener not persist to DB, why?

### ISSUE THREAD

**Issue by reypm** [1up-lab/OneupUploaderBundle#150]
I'm trying to upload one or more files using [OneupUploaderBundle][1] but I can not get it to work since files aren't uploaded and nothing is persisted to DB. I'll explain what I've done til now:

`config.yml`:

    oneup_uploader:
        mappings:
            recaudos:
                frontend: blueimp
                storage:
                    service:              ~
                    type:                 filesystem
                    filesystem:           ~
                    directory:            %kernel.root_dir%/../web/uploads/recaudos
                    stream_wrapper:       ~
                    sync_buffer_size:     100K
                allowed_mimetypes:     [application/msword,image/jpeg,image/pjpeg,image/png,application/pdf,application/vnd.oasis.opendocument.text]
                #disallowed_mimetypes:  []
                error_handler:        oneup_uploader.error_handler.noop
    
                # Set max_size to -1 for gracefully downgrade this number to the systems max upload size.
                #max_size:             9223372036854775807
                use_orphanage:        true
                enable_progress:      true
                enable_cancelation:   true
                namer:                oneup_uploader.namer.uniqid

At Twig template only this:

    <input id="fileUpload3" class="fileUpload" type="file" name="fileUpload3[]" data-url="{{ oneup_uploader_endpoint('recaudos') }}" multiple />
    
    $(document).ready(function(){
        $('fileUpload3').fileupload();
    });

And latest this is the Listener for `onUpload` event:

    namespace AppBundle\EventListener;
    
    use Oneup\UploaderBundle\Event\PostPersistEvent;
    use Symfony\Component\HttpFoundation\Request;
    use AppBundle\Entity;
    
    class UploadListener
    {
        protected $doctrine;
    
        public function __construct($doctrine)
        {
            $this->doctrine = $doctrine;
        }
    
        public function onUpload(PostPersistEvent $event, Request $request)
        {
            $session = $request->getSession();
            $em = $this->doctrine->getManager();
            $request = $event->getRequest();
            $tempfile = $event->getFile();
    
            $productoSolicitud = $em->getRepository('SolicitudProducto')->find($session->get('productoSolicitudId'));
    
            $recaudosTramiteProductoSolicitud = new Entity\RecaudosTramitesProductoSolicitud();
            $recaudosTramiteProductoSolicitud->setProductoSolicitud($productoSolicitud);
    
            $filenamePart = explode("--", $tempfile->getName());
            $pathinfo = pathinfo($tempfile->getName());
            $recaudosTramiteProductoSolicitud->setArchivo($pathinfo['filename']);
    
            $em->persist($recaudosTramiteProductoSolicitud);
            $em->flush();
        }
    }

And of course I have service defined also:

    appbundle.upload_listener:
        class: "AppBundle\EventListener\UploadListener"
        arguments:  [@doctrine]
        tags:
            - { name: 'kernel.event_listener', event: "oneup_uploader.post_persist", method: "onUpload" }

Did I miss something? Why file are not uploaded and data is not persisted? As you may see in the attached image there is a post request to `_uploader/recaudos/upload`, any advice?

![enter image description here][1] 

  [1]: http://i.stack.imgur.com/5pOFg.png

**Comment by stefanhuber** [comment]
Same problem...

**Comment by bytehead** [comment]
Is your event listener getting executed?

**Comment by stefanhuber** [comment]
the event listener is initialized by the container, but unfortunately the event got never fired/executed... In my configuration I had ```-1``` set for ```max_size```, because I want it to fall back on the php.ini configuration, as stated in the docs... However, with setting this for max_size (1) the file doesn't get moved after chunked upload and (2) the events don't get executed. Maybe there is a problem with this max_size parameter? Everything work brilliantly now...
