### ISSUE TITLE
Orphanage and thumbnails

### ISSUE THREAD

**Issue by Schyzophrenic** [1up-lab/OneupUploaderBundle#151]
Hello, 

I use the bundle with the blueimp uploader to upload pictures and then display them back to the user for cropping options. 
I would like to use the orphanage option, but in order to do that I need to define the orphanage directory as: 

```
%kernel.root_dir%/../web/uploads/orphans
```

Then the link sent back to the browser contains the session id. Is it something I can do or would I expose the site to security issues ?

Thanks for your help

**Comment by veloxy** [comment]
This is an old issue but for people ending up here I'd like to note that the session ID already is available to the client anyways (in your cookies). So this should be okay.

**Comment by Schyzophrenic** [comment]
This is an old case, but it is a useful answer, so I'll close the case 👍
