### ISSUE TITLE
Orphanage remove file before upload

### ISSUE THREAD

**Issue by sherif807** [1up-lab/OneupUploaderBundle#154]
I am using the Dropzone front end in a form. If a picture(s) is added it gets uploaded after form submit. Everything works well. The only thing. If a picture is added then removed. It still gets uploaded. I can listen to the remove event from Dropzone. But anyone knows how can I remove it from the pre upload orphanage folder? Or anyway to not upload it at all if removed?

**Comment by jokari4242** [comment]
+1
