### ISSUE TITLE
$file->getBasename() contains generic random string instead of original filename

### ISSUE THREAD

**Issue by ValentinSteiner** [1up-lab/OneupUploaderBundle#157]
I'm seeing a lot of uploaded files with 9 letter names composed of "php" and 6 random characters or numbers. Inside my custom Namer, $file->getBasename() returns strings like "phpcGqES2" or "phpDGMRwj".

I believe I've narrowed it down to small files (~500 KB) losing their names, whilst bigger files (~15 MB) tend to keep their original names. I suspect the filename handling differs between chunked uploads vs. non-chunked uploads..?

Using Fineuploader as the front end.

$request->get('qqfilename') returns the correct filename inside AbstractController->handleUpload(), so it looks like a problem inside OneUploader.

If I disable my custom Namer, OneUploader reverts to using uniqid() for the naming. Interesting enough, the resulting filename has a trailing dot and does not contain an extension, meaning $file->getExtension() also doesn't work under certain (probably the same) circumstances.

**Comment by fancyweb** [comment]
@ValentinSteiner

You can use `$file->getClientOriginalName()`to get the original file name in a custom namer because the `$file` is an instance of `Symfony\Component\HttpFoundation\File\UploadedFile`.

I think that, at this point, `$file->getBaseName()` returns the php temporary name of the file.
