### ISSUE TITLE
Seek before append

### ISSUE THREAD

**Issue by guilhermednt** [1up-lab/OneupUploaderBundle#161]
First of all, this is based on FineUploader, I don't know if other frontends would support what I propose here.

Currently the behavior for assembling chunks is to append the last one to the existing assembled file. This is causing files to be corrupted in the event of a connection fail.

Example:
Let's suppose the user had uploaded chunks 1 to 3 successfully, hence we have the assembled file like this:
`[chunk1][chunk2][chunk3]`

The user then uploads chunk 4 and the connection dies before a response is received. The assembled file will look like this:
`[chunk1][chunk2][chunk3][chunk4]`

At this point the state of the upload will be unsynchronised: the server will be waiting for chunk 5 and the user will try to send chunk 4 again.

What will happen is that the user will then send chunk 4 again and it will be appended to the assembled file, resulting in:
`[chunk1][chunk2][chunk3][chunk4][chunk4]`

Instead, what I propose is that we seek the file to the byte corresponding to the start of the chunk received (`qqpartbyteoffset`). This way then the user sends chunk 4 again it will only be overridden without major problems.

However, AFAIK, this can't be done currently because the StreamManager doesn't know the chunk's offset, even though this information comes in the user's request (`qqpartbyteoffset`).

**Comment by JHGitty** [comment]
We need to fix this before we could add support for concurrent chunking because I think on concurrent chunking this could be an issue.

**Comment by JHGitty** [comment]
@guilhermednt Do you like to help us to fix this issue?
