### ISSUE TITLE
Uploading a file heavier than php upload_max_filesize cause 500 error

### ISSUE THREAD

**Issue by fancyweb** [1up-lab/OneupUploaderBundle#164]
If I upload a file heavier than the php.ini `upload_max_filesize`, default event listeners (`MaxSizeValidationListener`, `AllowedMimetypeValidationListener`, `DisallowedMimetypeValidationListener`) cause 500 errors because they try to access the file size or mime type but cannot because the upload did not process.

Maybe we could check if the `$file` contains errors (by addding a `getUploadErrors()` method to the `FileInterface`) and throw an exception before the current listeners.

For `FilesystemFile` it looks easy because the class extends `Symfony\Component\HttpFoundation\File\UploadedFile` which has a `getError()` method.
For `GaufretteFile` I have no idea at the moment since I've never used it.

Edit : ok right now I've fixed it by adding another Validation listener with a higher priority, that throws an exception if `$file->getError()` is different than `UPLOAD_ERR_OK`.

**Comment by matatirosolutions** [comment]
I'm running into the same issue (file sizes too large) as you @fancyweb but I don't understand from your edit above how you're working around this - can you please provide an example/explanation of what you're doing..?

**Comment by matatirosolutions** [comment]
Did some more documentation digging and managed to figure out the workaround which @fancyweb was describing. Here for the benefit of others is what I've done. Create a listener:

```
<?php

namespace AppBundle\EventListener;

use Oneup\UploaderBundle\Event\ValidationEvent;
use Oneup\UploaderBundle\Uploader\Exception\ValidationException;

class UploadValidationListener
{
    public function onValidate(ValidationEvent $event)
    {
        if($event->getFile()->getError() != UPLOAD_ERR_OK) {
            throw new ValidationException('error.maxsize');
        }
    }
}
```

Then define that as a service in services.yml

```
upload.validation_listener:
            class: AppBundle\EventListener\UploadValidationListener
            tags:
                - { name: kernel.event_listener, event: oneup_uploader.validation, method: onValidate }
```
Which at least when using Dropzone as the uploader results in an acceptable UX.

**Comment by fancyweb** [comment]
@matatirosolutions 
```php
<?php

namespace ...;

use Oneup\UploaderBundle\Event\ValidationEvent;
use Oneup\UploaderBundle\Uploader\Exception\ValidationException;
use Oneup\UploaderBundle\UploadEvents;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class UploadListener implements EventSubscriberInterface
{
    /**
     * @return array
     */
    public static function getSubscribedEvents()
    {
        return array(
            UploadEvents::VALIDATION => array(
                'onValidation',
                255
            )
        );
    }

    // https://github.com/1up-lab/OneupUploaderBundle/issues/164
    /**
     * @param ValidationEvent $event
     * @throws ValidationException
     */
    public function onValidation(ValidationEvent $event)
    {
        $error = $event->getFile()->getError();
        if (UPLOAD_ERR_OK !== $error) {
            if (UPLOAD_ERR_INI_SIZE === $error) {
                throw new ValidationException('error.maxsize');
            } else {
                throw new ValidationException('error.other');
            }
        }
    }
}
```

**Comment by matatirosolutions** [comment]
Thanks @fancyweb a more complete solution than the one I'd come up with :-)

**Comment by fancyweb** [comment]
@matatirosolutions I just saw your solution which is very similar, but you should make sure your listener is run before the default validation listeners of this bundle or you might encounter the problem I have described in this issue.
