### ISSUE TITLE
Problem with Gaufrette 0.1.9

### ISSUE THREAD

**Issue by guilhermednt** [1up-lab/OneupUploaderBundle#169]
First of all, I cannot thank you enough for such a great bundle.

Secondly, I'm not sure if this is a Gaufrette's or an OneupUploaderBundle's bug. What I mean is that Gaufrette might have made a breaking change or that OneupUploaderBundle is misusing Gaufrette, so maybe that's the main question.

Now about the problem:

After updating a project to Gaufrette 0.1.9, upload stopped working. I noticed that the `oneup_uploader.post_upload` event was receiving a `File` pointing to the "chunked file" instead of the actual finished file.

After digging a bit I suspect the problem could be somewhere near `Oneup\UploaderBundle\Uploader\Storage\GaufretteStorage` at line 33:

``` php
$file->getFilesystem()->rename($file->getKey(), $path);

return new GaufretteFile($this->filesystem->get($path), $this->filesystem, $this->streamWrapperPrefix);
```

What happens is that after renaming the file on line 33 the `new GaufretteFile` of line 35 receives the previous, apparently cached, `File` instance from `$this->filesystem->get($path)`, but I don't know if this is the expected behavior or not.

**Comment by Jasonlgrd** [comment]
Hello, 

I have same problem. After upload last chunk and Gaufrette rename file, new key isn't accessible. New key is in fileSystem->fileRegister but fileRegister is protected. How is possible i can access in final key in event oneup_uploader.post_upload.gallery

![Capture d’écran 2021-11-03 à 08 52 09](https://user-images.githubusercontent.com/35960493/140025108-2204aa0d-f367-4cf5-af47-47d8bcfcb363.png)

Thank you !
