### ISSUE TITLE
Orphanage complaining about no running session

### ISSUE THREAD

**Issue by nmeirik** [1up-lab/OneupUploaderBundle#171]
I'm attempting to make use of the orphanage, but get the following exception when uploading:

`You need a running session in order to run the Orphanage.`

AFAIK I should indeed have a running session. It is worth pointing out, though, that my session setup is somewhat custom. Due to the SF-application being developed in conjunction with a legacy application also using sessions, I'm utilizing [the method described here](http://symfony.com/doc/current/cookbook/session/php_bridge.html) to bridge the legacy application with Symfony sessions. Could this have any impact on the use of the orphanage?

**Comment by sheeep** [comment]
Hmm, good question indeed. It seems [like your session is not started](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Uploader/Storage/FilesystemOrphanageStorage.php#L36). Do you know if other session related code works for your setup?

**Comment by nmeirik** [comment]
> Do you know if other session related code works for your setup?
It does appear that way. My basis for that assumption is that I'm logged in as a user as confirmed by the profiler toolbar.

**Comment by nmeirik** [comment]
Or maybe not. Doing the following in a random controller action:

```
$session = $this->container->get('session');
var_dump($session);
```
...produces the following output:
```

object(Symfony\Component\HttpFoundation\Session\Session)#65 (3) {
  ["storage":protected]=>
  object(Symfony\Component\HttpFoundation\Session\Storage\PhpBridgeSessionStorage)#64 (5) {
    ["bags":protected]=>
    array(2) {
      ["attributes"]=>
      object(Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag)#60 (3) {
        ["name":"Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag":private]=>
        string(10) "attributes"
        ["storageKey":"Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag":private]=>
        string(15) "_sf2_attributes"
        ["attributes":protected]=>
        array(0) {
        }
      }
      ["flashes"]=>
      object(Symfony\Component\HttpFoundation\Session\Flash\FlashBag)#59 (3) {
        ["name":"Symfony\Component\HttpFoundation\Session\Flash\FlashBag":private]=>
        string(7) "flashes"
        ["flashes":"Symfony\Component\HttpFoundation\Session\Flash\FlashBag":private]=>
        array(0) {
        }
        ["storageKey":"Symfony\Component\HttpFoundation\Session\Flash\FlashBag":private]=>
        string(12) "_sf2_flashes"
      }
    }
    ["started":protected]=>
    bool(false)
    ["closed":protected]=>
    bool(false)
    ["saveHandler":protected]=>
    object(Symfony\Component\HttpFoundation\Session\Storage\Proxy\NativeProxy)#61 (3) {
      ["wrapper":protected]=>
      bool(false)
      ["active":protected]=>
      bool(false)
      ["saveHandlerName":protected]=>
      string(5) "files"
    }
    ["metadataBag":protected]=>
    object(Symfony\Component\HttpFoundation\Session\Storage\MetadataBag)#62 (5) {
      ["name":"Symfony\Component\HttpFoundation\Session\Storage\MetadataBag":private]=>
      string(10) "__metadata"
      ["storageKey":"Symfony\Component\HttpFoundation\Session\Storage\MetadataBag":private]=>
      string(9) "_sf2_meta"
      ["meta":protected]=>
      array(3) {
        ["c"]=>
        int(0)
        ["u"]=>
        int(0)
        ["l"]=>
        int(0)
      }
      ["lastUsed":"Symfony\Component\HttpFoundation\Session\Storage\MetadataBag":private]=>
      NULL
      ["updateThreshold":"Symfony\Component\HttpFoundation\Session\Storage\MetadataBag":private]=>
      string(1) "0"
    }
  }
  ["flashName":"Symfony\Component\HttpFoundation\Session\Session":private]=>
  string(7) "flashes"
  ["attributeName":"Symfony\Component\HttpFoundation\Session\Session":private]=>
  string(10) "attributes"
}
```

I can see here that the started property is set to false, which I belive is what the orphanage checks. Should I do anything specific in order to start the session?

**Comment by sheeep** [comment]
[The guide you were following](http://symfony.com/doc/current/cookbook/session/php_bridge.html) mentions this:

> If you're integrating the Symfony full-stack Framework into a legacy application that starts the session with session_start(), you may still be able to use Symfony's session management by using the PHP Bridge session.

I guess Symfony is not marking the session as started. But if we can not test for `$session->isStarted()`, how would one do this? According to [the API docs](http://api.symfony.com/2.6/Symfony/Component/HttpFoundation/Session/Session.html), there is no other way to check for a started session.

**Comment by sheeep** [comment]
What about [this part of the component docs](http://symfony.com/doc/current/components/http_foundation/session_php_bridge.html):

```php
// Get Symfony to interface with this existing session
$session = new Session(new PhpBridgeSessionStorage());

// symfony will now interface with the existing PHP session
$session->start();
```

I wonder what this means for your application:

> Additionally, it is mandatory for Symfony to start the session.

**Comment by nmeirik** [comment]
I have to admit that this is slightly over my head. I would expect the security.context service to interact with the user session in a similar way, but doing something like `$this->get('security.context')->getToken()->getUser();` works fine.

**Comment by nmeirik** [comment]
I have rewritten my legacy application to make use of the SF session component, but still keeping the PHPBridgeSessionStorage. However, I no longer make use of a specific `storage_id´and `handler_id`as mentioned in the initial post. Still, the orphanage controller action complains about the session not existing. Should not SF start the session by itself? I mean, there's no need for me to do any kernel event listeners in order to start the session, is there?

**Comment by sheeep** [comment]
Any news on this? I guess this is not a problem of this bundle, but somehow of the bridged session handler? Ping me, if I should reopen this ticket.

**Comment by tlorens** [comment]
2017 and I'm having this exact same problem.  From what I've read here, it would appear to be a Symfony/PHPBridge problem.

**Comment by tlorens** [comment]
What's interesting about this is, I've commented out `isStarted()` check and littered the code with some `error_log()` to see the process through-- it works..  
```

[notice] A handleUpload::before upload
[notice] B FilesystemOrphanageStorage::upload function
[notice] getPath: 66c2269ec0316b8e7f76f22fbd5aef3a
[notice] C FilesystemStorage::parent::upload
[notice] D handleUpload::after upload
```

You see in the getPath function it fetches the session ID.  It's listed there above.   Echoing out the isStarted() result is still `=== false`.  I'm going to dive into the PhpBridgeSession thing next.

**Comment by tlorens** [comment]
So in my `UploadChunkController.php` I've added 

```
        $session = $request->getSession();
        $session->start();
```
At the beginning of the `handleUpload($file...)` function.  Seems to resolve the issue.
