### ISSUE TITLE
GET /_uploader/gallery/upload

### ISSUE THREAD

**Issue by Sashkan** [1up-lab/OneupUploaderBundle#173]
I'm trying to upload files using Dropzone, everytime I do so, files are uploaded, but I get to an error page with "No route found for "GET /_uploader/gallery/upload": Method Not Allowed (Allow: POST)".

Here's my service : 
``` PHP
        aofvh_user.upload_listener:
        class: AOFVH\UserBundle\EventListener\UploadListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }
```

and my Listener

``` PHP
<?php
namespace AOFVH\UserBundle\EventListener;

use Oneup\UploaderBundle\Event\PostPersistEvent;

class UploadListener
{
    public function __construct($doctrine)
    {
        $this->doctrine = $doctrine;
    }

    public function onUpload(PostPersistEvent $event)
    {

    }
}
```

**Comment by behrus** [comment]
Hi there, did you find a solution. I have the same problem. This happens if i upload all file by. Single upload is ok.

**Comment by sheeep** [comment]
There seems to be a problem with your HTML/JavaScript integration of Dropzone, as you both get redirected to the upload route. (Be sure to use `POST`, `PUT` or `PATCH` when uploading files.)

**Comment by armilleiwilliam** [comment]
This is my code in the HTML and I get the same problem:

<script src="https://rawgit.com/enyo/dropzone/master/dist/dropzone.js"></script>
<link rel="stylesheet" href="https://rawgit.com/enyo/dropzone/master/dist/dropzone.css">
<form action="{{ oneup_uploader_endpoint('gallery') }}" class="dropzone" method="POST" >
</form>


Did you found a solution?
