### ISSUE TITLE
jQuery-File-Upload not showing his front-end

### ISSUE THREAD

**Issue by luismabenitez** [1up-lab/OneupUploaderBundle#174]
I'm having troubles because the bundle is working -files are uploaded perfectly to the right place- but in my template the plugin shows only a file input box and all three jquery files are correctly opened... Any idea?

**Comment by luismabenitez** [comment]
If I choose the Dropzone's plugin, it works perfectly. But looks like jQuery files are not working correctly, but are opened and not problems in console... Any idea or somebody who has same problem?

**Comment by AlexGodard** [comment]
I'm having the same problem with blueimp jquery plugin.

**Comment by sheeep** [comment]
> shows only a file input box and all three jquery files are correctly opened...

Can you be a bit more specific?

**Comment by darthf1** [comment]
Maybe i can be of assistance. I've copy /paste the snippets from [this](http://stackoverflow.com/questions/26341843/simple-example-of-the-entity-file-to-be-uploaded-with-oneupuploaderbundle) url.

As a result, the normal HTML5 file upload button is displayed. No fancy jquery file uploader.
