### ISSUE TITLE
Problems with re intent with file upload.

### ISSUE THREAD

**Issue by mrtnzagustin** [1up-lab/OneupUploaderBundle#176]
Hi to all. First, here's my configuration with plupload:
                        runtimes: 'html5,flash,silverlight,html4',
                        url: "{{ oneup_uploader_endpoint('gallery') }}",
                        views: {
                            list: true,
                            thumbs: false,
                            active: 'list'
                        },
                        multipart_params : { "token" : token},
                        rename: true,
                        required_features: true,
                        unique_names: true,
                        max_retries: 5,
                        sortable: true,
                        buttons: {
                            browse: true,
                            start: true,
                            stop: false
                        },
                        filters: {
                            mime_types: [
                                {title: "Archivos de Imagen", extensions: "jpg,jpeg,png"}
                            ],
                            prevent_duplicates: true
                        },
                        max_file_size: "25mb",
                        // Flash settings
                        flash_swf_url: 'http://www.plupload.com/examples/plupload/js/Moxie.swf',
                        // Silverlight settings
                        silverlight_xap_url: 'http://www.plupload.com/examples/plupload/js/Moxie.xap',
With the bundle, just :

oneup_uploader:
    mappings:
        gallery:
            frontend: plupload

My problem is that sometimes the files are not being uploaded and the result of the "post" its a 200 code. Like you see, I have the max_retries option in 5. I have no idea where the problem is.

Regards,
Agustin

**Comment by sheeep** [comment]
I'm sorry, but I have no idea given the information you provided. If the problem persists, can you create a new bare-bone Symfony project, and re-create the error, so I can take a look?

**Comment by mrtnzagustin** [comment]
Hi there. Sorry for the late response. The problem was with APACHE and the max_input_time variable!
Thanks!

Agustin
