### ISSUE TITLE
Change destination folder

### ISSUE THREAD

**Issue by JapanKyutsu** [1up-lab/OneupUploaderBundle#179]
Hello,

Can you give best practices in order to change the default directory of uploaded files (web/uploads/gallery) ? 

It would be great if you can use for example some form data (album slug if you are uploading photos into an album) or just simple thing like the year or the month because currently all uploaded files are going in a same directory which is hard to maintain

Thanks

**Comment by bytehead** [comment]
You can change the default directory via [configuration](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/configuration_reference.md).
If you want to use a dynamic directory, use a [custom namer](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_namer.md), see also #250.
