### ISSUE TITLE
How to get the name of the file

### ISSUE THREAD

**Issue by armilleiwilliam** [1up-lab/OneupUploaderBundle#182]
Hi,
I want to get the file original name but it seems that the system translate it in a string of numbers instead of returning the original name file. I used the following methods:
$file->getFilename()
$file->getBasename()
$file->getPathname()
None of them give the original file name somehow, but only a string of  number, probably an md5 translation of the file coded somewhere in the bundle. Can anybody tell me how to get the original file name? Thanks.

**Comment by bytehead** [comment]
You should use your own [namer](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_namer.md) in this case.

**Comment by armilleiwilliam** [comment]
Thanks, but it doesn't get the real name of the file, right? I'm creating an application where the file name uploaded by the client have to be stored in a database to be shown in the list of the file uploaded on a page. Is there a way to get the real file name instead of creating it by myself with the namer?

**Comment by armilleiwilliam** [comment]
By the way, I passed by Lucerne only 2 weeks ago. I live in Italy and was going to Bern ;-)

**Comment by bytehead** [comment]
Did you try `$file->getClientOriginalName()`?

**Comment by armilleiwilliam** [comment]
getClientOriginalName() is not among the methods available. I had already tried it.

**Comment by bytehead** [comment]
Maybe not visible in your IDE, but it should work...

**Comment by armilleiwilliam** [comment]
OK, this is what I've done. With an ajax calling i sent data to the following function which works fine if i use $file->getFileName(), but when I use $file->getClientOriginalName() instead of getFileName it doesn't work:

public function onUpload(PostPersistEvent $event)
    {
        $file = $event->getFile();
if ($request->get('attachment')) {
      $contratto = $em->getRepository('CasaFront2Bundle:Contratto')->find($request->get('attachment'));
        $documento = new Documento();
       $documento->setFile('upload/'.$contratto->getId().'/documenti/'.$file->move('upload/'.$contratto->getId().'/documenti/',  $file->getClientOriginalName())->getClientOriginalName());
$documento->setContratto($contratto);
      
   
                $em->persist($documento);
                $em->flush();
}}

**Comment by bytehead** [comment]
I'm not sure, if you have to use the onUpload event. Just use the namer as this:

```php
<?php

namespace Acme\DemoBundle;

use Oneup\UploaderBundle\Uploader\File\FileInterface;
use Oneup\UploaderBundle\Uploader\Naming\NamerInterface;

class OriginalNameNamer implements NamerInterface
{
    public function name(FileInterface $file)
    {
        return $file->getClientOriginalName());
    }
}
```

**Comment by armilleiwilliam** [comment]
I don't know how to integrate the code you gave me with the one I just posted before. I tried to do something like this but it's not working. I don't know if $this->name($event) in the following code is right. 


use Oneup\UploaderBundle\Event\PostPersistEvent;
use Casa\Front2Bundle\Entity\Foto;
use Casa\Front2Bundle\Entity\Documento;
use Oneup\UploaderBundle\Uploader\File\FileInterface;
use Oneup\UploaderBundle\Uploader\Naming\NamerInterface;
use JF\UtilityBundle\Controller\Traits\OriginalNameNamer;

class UploadListener implements NamerInterface
{
 



    public function name(FileInterface $file)
    {
        return $file->getClientOriginalName();
    }
    public function onUpload(PostPersistEvent $event)
    {
        $file = $event->getFile();
        /* @var $file \Symfony\Component\HttpFoundation\File\File */

        $request = $event->getRequest();

        $response = $event->getResponse();
        $r = array();

        $em = $this->doctrine->getEntityManager();

  if ($request->get('attachment')) {
      $contratto = $em->getRepository('CasaFront2Bundle:Contratto')->find($request->get('attachment'));
        $documento = new Documento();
       $documento->setFile('upload/'.$contratto->getId().'/documenti/'.$file->move('upload/'.$contratto->getId().'/documenti/',  $this->name($event))->getFileName());

                $em->persist($documento);
                $em->flush();

        }

**Comment by bytehead** [comment]
You just have to follow the instructions [here](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_namer.md):

1. Set up the `OriginalNameNamer` as mentioned [before](https://github.com/1up-lab/OneupUploaderBundle/issues/182#issuecomment-112503172)
2. Register your namer in the `services.xml`
3. Adding the custom service to your configuration

**Comment by armilleiwilliam** [comment]
Ok, I've followed your instructions. But it gives me an error when I write something like this:
oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp
            namer: acme_demo.custom_namer

If I take away frontend it gives me an error, so I've put both.

**Comment by armilleiwilliam** [comment]
Sorry, I was wrong, not it works. THANKSSSSS SO MUCH!!! SORRY FOR BOTHERING YOU SO MUCH. 

LUCERN IS SUCH A GREAT CITY ;-)

**Comment by bytehead** [comment]
You're welcome! :)

**Comment by maztch** [comment]
Because I don't want the file on system have the client filename to avoid conflicts and for security so I don't want to set the Namer. 

You can use this so fill your entity. I just get the name from the request on the upload event and return it on the response:

    class UploadEvent
    {
        //return the file name on server plus the original filename
        public function onUpload(PostPersistEvent $event)
        {
            $response = $event->getResponse();
            //if everything went fine, return the response
            $response['success'] = true;
            //the filename
            $response['file_name'] = $event->getFile()->getFilename();

            //the original filename
            $response['file_original_name'] = $event->getRequest()->files->get('file')->getClientOriginalName();
            return $response;
        }
    }
