### ISSUE TITLE
FatalErrorException with chuking enable

### ISSUE THREAD

**Issue by DerpDarako** [1up-lab/OneupUploaderBundle#193]
Hello,

When i try to upload a file with pluploader and your bundle, Symfony catch this FatalErrorException:

FatalErrorException: Error: Call to undefined method ArrayIterator::getInnerIterator() in /appli/web/crt-rso/vendor/oneup/uploader-bundle/Oneup/UploaderBundle/Uploader/Chunk/Storage/FilesystemStorage.php line 59

You will find below more informations about my software:

PHP : 5.3.3
Symfony : 2.3.33
Apache :  2.2.15

Is it possible to fix it by myself?

**Comment by bytehead** [comment]
This is probably fixed in 1ffd96c74e3d456a241138e4d80d1f99e5216f0c.
