### ISSUE TITLE
Support for Symfony3

### ISSUE THREAD

**Issue by JHGitty** [1up-lab/OneupUploaderBundle#200]
Is this bundle ready for Symfony3?

**Comment by lsv** [comment]
Not the latest tag 1.3.1 but master is

@sheeep or @mitom could we get a new tagged version for Symfony 2.8 + 3.0 ?

**Comment by SakyaStelios** [comment]
+1

**Comment by JHGitty** [comment]
ping @sheeep @bytehead

**Comment by lsv** [comment]
I just found out that I have made som changes directly in the code.

You cant get Request from the container anymore, you need to get Request_Stack and then getMasterRequest.

I will have a PR up tomorrow - and with that PR, I have tested upload and response in Symfony 3 (but not orphange stuff)

**Comment by lsv** [comment]
PR #202 is up

**Comment by bytehead** [comment]
Closed in favor of #202.
