### ISSUE TITLE
How to prevent upload?

### ISSUE THREAD

**Issue by JHGitty** [1up-lab/OneupUploaderBundle#201]
How can I prevent the upload in special cases? I like to have a custom logic which will trigger into a custom error message in special cases. I use ``FineUploader``. How can I do it?

Can I use the event system to return a custom response (FineUploaderResponse?)? If yes: How can I set the response in the event listener?

**Comment by bytehead** [comment]
Does https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_error_handler.md or #208 help with your question?

**Comment by JHGitty** [comment]
The new documentation of #208 helped me. Thanks!
