### ISSUE TITLE
Get $request through function parameter

### ISSUE THREAD

**Issue by JHGitty** [1up-lab/OneupUploaderBundle#203]
I think this line is not required:
https://github.com/lsv/OneupUploaderBundle/blob/1fd249208fd44bb89ebd93a21d8a7e6f2f9af505/Controller/AbstractChunkedController.php#L48

The ``$request`` is already passed through the function parameter.

**Comment by bytehead** [comment]
Please comment on the PR instead of opening issues.

**Comment by JHGitty** [comment]
This issue should be fixed by #202 
https://github.com/lsv/OneupUploaderBundle/commit/42ee22e20fb113e5f0b3b4a6606b3c1fd0c3cee8#diff-0dafdc09a6cfedf2272a133fe05a69b7L48
