### ISSUE TITLE
how to get last version of this bundle by composer - I'm missing thing which has been fixed allready

### ISSUE THREAD

**Issue by milan74sk** [1up-lab/OneupUploaderBundle#205]
In my symfony2 project - composer.json I have:
...
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        ...
        "oneup/uploader-bundle": "~1.3"
    },
...

but still occurs the error which you fixed in commit:
https://github.com/1up-lab/OneupUploaderBundle/commit/1ffd96c74e3d456a241138e4d80d1f99e5216f0c

and still see in the code the old call of iterator ...

what I should put in my composer ?

thanks

**Comment by bytehead** [comment]
You should be able to use `"oneup/uploader-bundle": "dev-master"`.
If it doen't work with Symfony 2.8, try `"oneup/uploader-bundle": "dev-release-1.4.0"`.

**Comment by milan74sk** [comment]
Thank you very much, ""oneup/uploader-bundle": "dev-master"" works with no problem

**Comment by bytehead** [comment]
No worries. Just pay attention to updates, dev-master has not to be stable. 
We are currently working on a new release, so change back to the new release version constraint then.
