### ISSUE TITLE
File uploader support request

### ISSUE THREAD

**Issue by andreaslarssen** [1up-lab/OneupUploaderBundle#206]
How about supporting [Angular File Upload](https://github.com/nervgh/angular-file-upload)?

**Comment by bytehead** [comment]
You're always welcome to provide a pull request with that feature :)

**Comment by andreaslarssen** [comment]
If I end up using that lib and OneUp, I will. For now, I'm researching other ways of chunk uploading files.

**Comment by JHGitty** [comment]
You may use FineUploader - it has support for chunk uploading files.

**Comment by andreaslarssen** [comment]
Ended up using another lib.
