### ISSUE TITLE
Symfony3 installation error

### ISSUE THREAD

**Issue by milan74sk** [1up-lab/OneupUploaderBundle#210]
everything set up against the documentation
composer update
...
and lot of errors:
first one in list is:
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Fatal error: Call to undefined method Symfony\Component\DependencyInjection\Definition::setScope()
in d:\projects\s3test\vendor\oneup\uploader-bundle\Oneup\UploaderBundle\DependencyInjection\OneupUploaderExtension.php on line 118
...

**Comment by bytehead** [comment]
Did you try it with [release-1.4.0](https://github.com/1up-lab/OneupUploaderBundle/tree/release-1.4.0) ?

**Comment by milan74sk** [comment]
with this version it was:
...
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package oneup/uploader-bundle could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
...

but now I have not time to research it, I'll take a deep look on it after holiday

**Comment by mogilvie** [comment]
Release 1.4.0 works in my Symfony2  3.0.* test application.
My composer entry looks like:  "oneup/uploader-bundle": "dev-release-1.4.0"
