### ISSUE TITLE
Orphanage: Setting upload directory in controller

### ISSUE THREAD

**Issue by rvmourik** [1up-lab/OneupUploaderBundle#219]
Hi There,

I'm using the bundle with Orphanage and the newly implemented Flysystem. It's working like a charm, but i'm trying to do the following:

When executing the uploadFiles method in the Controller which handles the uploading to Flysytem, i would like to determine the directory in which the files need to be uploaded. Every entity has it's own directory in the filesystem.

Can this be easily done, or do i need to move the files after they are succesfully uploaded?

Thanks.

Robbert

**Comment by rvmourik** [comment]
Is there anyone who can give me a pointer here, i would really like to prevent writing a custom uploader for this.

Thanks in advance.

**Comment by bytehead** [comment]
Maybe you could achieve your goal with a custom namer?
