### ISSUE TITLE
Support Concurrent Chunking (FineUploader)

### ISSUE THREAD

**Issue by ghost** [1up-lab/OneupUploaderBundle#221]
http://docs.fineuploader.com/features/concurrent-chunking.html#server-side-implications

I think we need to fix this issues first: https://github.com/1up-lab/OneupUploaderBundle/issues/222 https://github.com/1up-lab/OneupUploaderBundle/issues/161

**Comment by zelding** [comment]
I've created a version which uses concurrent chunking, but it is mostly untested right now.
Please try it if you have the time.

Also some feedback would be nice from the owner too @bytehead ;)

[My fork](https://github.com/zelding/OneupUploaderBundle)

**Comment by JHGitty** [comment]
@zelding What's about providing a pull request? :-)

**Comment by zelding** [comment]
I rather not create a pull request to the master branch, because I've edited even the readme file, and most of it is untesed. I think it will do more harm than good, but im open to suggestions.
