### ISSUE TITLE
Rename feature if file already exists

### ISSUE THREAD

**Issue by ghost** [1up-lab/OneupUploaderBundle#223]
Example: The file name `test.zip` already exists.
1. Try `test.1.zip` or `test.2.zip` or ...
2. Try `test.TIMESTAMP.zip`. `TIMESTAMP` will be replaced by the current timestamp.
3. Something else.. (own code?)

The seperator must not be a dot. It also might be an underscore or something else:
`test.1.zip` or `test_1.zip` or `test-1.zip` or `test1.zip` or `test(1).zip`.

We also need new configuration features:
1. How often should we re-try file naming? This should be `3` or `5` or `10` by default.
2. How should the renaming work? Increase numbers or timestamp or own code? This might be done similar as the naming system with own classes.

**Comment by JHGitty** [comment]
Idea for default behaviour. Example: The file ``test.zip`` already exist.

1. Try ``test_1.zip`` or ``test1.zip`` or ``test.1.zip``.
2. Try ``test_TIMESTAMP.zip``. ``TIMESTAMP`` will be replaced by the current timestamp.
