### ISSUE TITLE
Do you have functional demo?

### ISSUE THREAD

**Issue by estebannovo** [1up-lab/OneupUploaderBundle#226]
very good job, any demo to see te functionality?

**Comment by p1rox** [comment]
+1

**Comment by bytehead** [comment]
There is an extensive example on [stackoverflow](http://stackoverflow.com/questions/26341843/simple-example-of-the-entity-file-to-be-uploaded-with-oneupuploaderbundle) :)

**Comment by p1rox** [comment]
Yes, I know but I'm stuck on an error
```
[Symfony\Component\Debug\Exception\ContextErrorException]
Catchable Fatal Error: Argument 1 passed to FileManagerBundle\EventListener\UploadListener::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, none given, called in /Users/armand/Callery/app/cache/dev/app
DevDebugProjectContainer.php on line 820 and defined
```
Should I open a seperate ticket ?

**Comment by cAstraea** [comment]
Trying to follow the example but seems only basic unless I've missed something nothing really happens 
expect the file gets uploaded and the listener event fires.

Trying to accomplish something among the lines of https://blueimp.github.io/jQuery-File-Upload/index.html
where i would see the actual file after uploading and be able to delete it but no idea where to begin ~

**Comment by sheeep** [comment]
> Trying to follow the example but seems only basic unless I've missed something nothing really happens 
expect the file gets uploaded and the listener event fires.

This is the only thing that is the same in every kind of application. File uploads are tight coupled with the logic of your application. Any example that is not basic would only fit a single use case and is not necessarily useful for anyone. The example provided in the StackOverflow question/answer is a bit more straight forward. It stores a reference to the uploaded file in an entity. From there it should be an easy task to create a route which deletes an image or from where you can get a preview from.

You need to understand the scope of this bundle. It only handles a file *upload* part of your application.
