### ISSUE TITLE
Support FileType field

### ISSUE THREAD

**Issue by ghost** [1up-lab/OneupUploaderBundle#232]
I like to have support for the `FileType` field to upload files. 
http://symfony.com/doc/current/reference/forms/types/file.html

**Comment by darthf1** [comment]
So this means if I use the FileType it's not working? What type should I be using instead?
What needs to be done (which files to edit) to support the FileType field?

**Comment by JHGitty** [comment]
The issue is that currently all the upload code is done by the controller classes. There is currently no support for form fields in this bundle. But it would be very nice if anybody would add support for it.
