### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by deviprsd21** [1up-lab/OneupUploaderBundle#237]
In the documentation of [Chunked clear up command](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/chunked_uploads.md#clean-up)
```
$> php app/console oneup:uploader:clean-chunks
```
It should be
```
$> php app/console oneup:uploader:clear-chunks
```

**Comment by JHGitty** [comment]
@deviprsd21 Do you please to create a Pull Request? You can do it directly on GitHub.

**Comment by deviprsd21** [comment]
@JHGitty yeah I could have, just didn't think to create a pull request for a small issue, but never mind, I'll make one.

**Comment by sheeep** [comment]
Thanks!
