### ISSUE TITLE
Documentation for plupload v1, but no v2

### ISSUE THREAD

**Issue by aistis-** [1up-lab/OneupUploaderBundle#239]
The documentation at [docs](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/frontend_plupload.md) is for [plupload](http://www.plupload.com/) `v1` while `v2` is already released some time ago.

**Comment by JHGitty** [comment]
Is version 2 already supported or do we need to add additional code to support version 2?

**Comment by JHGitty** [comment]
Did you successfully test version 2 with this bundle?
