### ISSUE TITLE
Support FineUploader Resume feature

### ISSUE THREAD

**Issue by ghost** [1up-lab/OneupUploaderBundle#240]
We should provide support for the Resume feature of FineUploader.

http://docs.fineuploader.com/branch/master/features/resume.html

As I understand we already support chunking but not these special resume features (`resume.recordsExpireIn` option and reset response on missing/invalid data).

**Comment by rnicholus** [comment]
Hey there, this case just appeared on my radar. If you run into any Fine Uploader related issues implementing this, feel free to let me know by opening up a case in the Fine Uploader issue tracker (or simply comment here).
