### ISSUE TITLE
Passtrough request to namer class

### ISSUE THREAD

**Issue by ghost** [1up-lab/OneupUploaderBundle#243]
We should inject the `@request_stack` to the namer class.

Thanks to @nomadOnWeb for this idea (#228).

**Comment by JHGitty** [comment]
@bytehead This will result into a BC break. Do you like to directly merge it into a new version if I create a PR for it? Which version of this bundle does allow BC breaks?

**Comment by JHGitty** [comment]
We should just add `RequestStack $requestStack` as argument to the constructor. :+1:

**Comment by mablae** [comment]
Should be added to the docs for slow folks like myself ;-)
