### ISSUE TITLE
Is this bundle compatible with Symfony3 ?

### ISSUE THREAD

**Issue by eved42** [1up-lab/OneupUploaderBundle#247]
I tried to install OneupUploaderBundle on a symfony3 project and appearently, it requires sonata media bundle, which is not compatible with symfony3.

Is there a way to install your bundle ?

**Comment by bytehead** [comment]
There is no dependency on sonata media bundle, see [composer.json](https://github.com/1up-lab/OneupUploaderBundle/blob/master/composer.json).
Our bundle should be compatible with Symfony ~3.0 (afaik).

**Comment by eved42** [comment]
Sorry, I tried to install sonata media bundle before but installation failed and my composer.json kept the requirements, so I couldn't install your bundle.

I tested it once again and your bundle was successfully installed. Thanks (and sorry).

**Comment by bytehead** [comment]
No worries, your're welcome!
