### ISSUE TITLE
DeleteFile GAP

### ISSUE THREAD

**Issue by parashutiki** [1up-lab/OneupUploaderBundle#251]
This implementation is required as required upload event.
Please describe how to implement deleteFile ... on Fine Uploader example.

I understand that the bundle only upload files ... but if i press trash in uploader it do nothing  ... sorry - return error.

**Comment by parashutiki** [comment]
Ok found where was problem:
// routing.yml
oneup_uploader:
    resource: .
    type: uploader
    methods: [DELETE, POST]

**Comment by sheeep** [comment]
Please check the [FAQs](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/index.md#faq)

> Why didn't you implement the delete feature provided by Fine Uploader?

> FineUploaders delete Feature is using generated unique names we would have to store in order to track down which file to delete. But both the storage and the deletetion of files are tight-coupled with the logic of your very own implementation. This means we leave the delete Feature open for you to implement. Information on how the route must be crafted can be found on the official documentation and on the blog of Fine Uploader.

You need to create a Controller and implement the deletion feature yourself. Unfortunately there is no way we can predict the type of deletion behaviour you need for your specific application. This is therefore out of scope for this bundle. 

But basically you [return a file id or entity id](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/response.md) (or however your application works) back to the frontend uploader which will then know how to call a route that deletes this specific file. Take a look at the [official Fine Uploader docs on this topic](http://docs.fineuploader.com/features/delete.html).

```js
var uploader = new qq.FineUploader({
    deleteFile: {
        endpoint: '{{ path('your-delete-route') }}'
    }
});
```

**Comment by parashutiki** [comment]
Of course I wrote my own Controller.
The problem that people install this module and research code for delete files.
It's like bear + toilet. I spent time for install and explore this Bundle and will write own controller.
