### ISSUE TITLE
Chunked file upload of big (more then 10MB) is broken

### ISSUE THREAD

**Issue by piotr-szegda** [1up-lab/OneupUploaderBundle#253]
For same time chucked file upload in broken. Only last chunk is saved.
Simple environment to reproduce problem: https://github.com/piotr-szegda/OneupUploaderBundleTest
I am using PHP 7.0.

**Comment by sheeep** [comment]
Thank you for reporting this issue. I'm afraid I can't reproduce this on my machine. I tried it with the following changes to your env:

```js
{
    maxChunkSize: 2048000
}
```

I needed to lower the maxChunkSize to respect my systems `max_upload_size`. Can you elaborate a bit more on whats going on? Are chunked uploads for smaller chunks (>10MB) working?

**Comment by piotr-szegda** [comment]
@sheeep thank you for interesting. With small chunk it's almost working because sha1 is correct but file is still in storage/upload/chunks/e39f9bfb44fe63516ca5512b28d77701/ instead of storage/upload/main.
With bigger chuck size, file is only last chunk. I have this problem on local dev env and prod server.
This is last request log: https://gist.github.com/piotr-szegda/1c19c64b86f2b45fea0740166813ad7b
PHPINFO: https://gist.github.com/piotr-szegda/f41f0ee22661290da6330916807ce77d

**Comment by piotr-szegda** [comment]
Removing `$this->validate($file); `in `protected function handleUpload($file, ResponseInterface $response, Request $request)` fix this problem but I don't know why.

**Comment by bytehead** [comment]
Removing the validation does obviously not fix the problem ;-)

**Comment by piotr-szegda** [comment]
@bytehead: Obviously you are right but it is a start point to debug why in some environments this issue exist.

**Comment by piotr-szegda** [comment]
I found source of this bug. I set max_size to -1 but MaxSizeValidationListener not working properly becouse recognizing every file as too large.
According to the Configuration Reference:
Set max_size to -1 for gracefully downgrade this number to the systems max upload size

**Comment by Rikijs** [comment]
@piotr-szegda cold you please share your working `oneup_uploader` configuration?

**Comment by piotr-szegda** [comment]
@Rikijs: Here you are!
```
oneup_uploader:
    mappings:
        main_file_upload:
            frontend: blueimp
            storage:
                  type: flysystem
                  filesystem: oneup_flysystem.temp_filesystem
            max_size:             4294967296
            #use_orphanage:        false
            enable_progress:      true
            enable_cancelation:   true
    chunks:
            maxage: 86400
            storage:
                directory:          "%kernel.root_dir%/../var/storage/upload/chunks"
                type:               filesystem`

oneup_flysystem:
     adapters:
         local_main_adapter:
             local:
                 directory: "%kernel.root_dir%/../storage/local_files"
         local_temp_adapter:
             local:
                 directory: "%kernel.root_dir%/../storage/local_tmp_files"
         local_public_adapter:
             local:
                 directory: "%kernel.root_dir%/../web/file"
     filesystems:
         temp:
             adapter: local_temp_adapter
             mount: local_temp
         local_main:
             adapter: local_main_adapter
             mount:   local_main
         local_public:
             adapter: local_public_adapter
             mount:   local_public`
```

**Comment by cassianotartari** [comment]
@piotr-szegda I'm facing the same problem and I think this is related to environment. I was developing under a ``Vagrant Homestead`` running ``php7 fpm`` and ``nginx``. But now I'm trying to configure the production server and stuck with this chunk problem. Probably we are missing some module or configuration, I'm looking at Homestead scripts right now https://github.com/laravel/homestead/tree/master/scripts

**Comment by jamescdavis** [comment]
Make sure in php.ini that post_max_size >= your chunk size.

**Comment by cassianotartari** [comment]
I've gave up to configure nginx + php7 with chunked uploads. Just did a fresh install using debian repositories for apache and php7 fpm and works great.
