### ISSUE TITLE
Reliance on non-core functionality in Flysystem

### ISSUE THREAD

**Issue by snarktooth** [1up-lab/OneupUploaderBundle#255]
The current release of Flysystem moved some methods from the core Flysystem class into plugins.  This bundle's implementation of the FlysystemOrphanageStorage class relies on the listFiles method, which is one of the affected methods.  This means that a project using Flysystem storage for the orphanage must ensure that Flysystem is configured to load the ListFiles plugin.  I have provided PR #252 which works around this dependency by changing the implementation to rely on core Flysystem functionality only.

**Comment by bytehead** [comment]
Fixed in #252.
