### ISSUE TITLE
UploadListener is not called

### ISSUE THREAD

**Issue by Rikijs** [1up-lab/OneupUploaderBundle#260]
I have set up OneUpUploaderBundle with three upload libraries.
I used: `FineUploader` library, `Blueimp` library and `Plupload` library on 3 different Symfony test projects.

All three instances upload files to the endpoint without issues.
However, upload listeners are not called and are displayed in `Symfony3 Profiler` > ` Events` section `Not Called Listeners`!

I have read all pull requests and issues on this projects Github page, still no suggestions worked! Additionally I have searched StackOverflow trough and trough, but did not found anything to fix my problem.

More detailed explanaton and exact code used can be found on StackOverflow:
 - [OneUpUploaderBundle with Fine Uploader](http://stackoverflow.com/questions/38055561/symfony-3-1-and-oneupuploaderbundle-fineuploader-uploadlistener-is-not-calle) question
 - [OneUpUploaderBundle with Blueimp](http://stackoverflow.com/questions/38295832/symfony-3-1-and-oneupuploaderbundle-blueimp-uploadlistener-is-not-called) question
 - [OneUpUploaderBundle with Plupload](http://stackoverflow.com/questions/38425818/symfony-3-1-and-oneupuploaderbundle-plupload-uploadlistener-is-not-called) question

Please advise.
Thank You for your time and knowledge.

**Comment by piotr-szegda** [comment]
Probably my issue is related: https://github.com/1up-lab/OneupUploaderBundle/issues/253
In my case listeners are also not called so it's break thing connected with chunk (but not only). In my case is environment related because it's cannot be reproduced on other. Unfortunately I can't find reason.

**Comment by Rikijs** [comment]
Yes, I am using `PHP v7.0.8` (newest as of time of writing) on `Windows 10 Pro`.
For development i am using `PHP built in server`.
I have not tested it yet in production with `Apache server`.

**Comment by piotr-szegda** [comment]
If you still have this issue check my #253.Perhaps it is the same problem

**Comment by Sander-Toonen** [comment]
@Rikijs In case you just switched over to php7, have you set the values of ``post_max_size`` and ``upload_max_filesize`` to big enough values in your php.ini file?

**Comment by Rikijs** [comment]
This issue was caused by misconfiguration of `services.yml`. Instead of `oneup_uploader.post_persist.gallery` instead of `...default_uploader` works. Curiously `.default_uploader` was only auto complete item that PHPStorm offered. In the meantime events are still shown in Event Dispather Not Called Listeners section, though I can confirm that events now fire as codein them executes and saves info about files to database.
