### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by theLordz** [1up-lab/OneupUploaderBundle#263]
Hello!

Oneup\UploaderBundle\Uploader\Chunk\Storage\FlysystemStorage.php -> $this->filesystem->listFiles -> throws BadMethodCallException with message: Call to undefined method League\Flysystem\Filesystem::listFiles with league/flysystem (1.0.27)

Thank you.

**Comment by sheeep** [comment]
In the current version the `listFiles` method is a plugin. https://github.com/thephpleague/flysystem/blob/master/src/Plugin/ListFiles.php

This might be a dependency problem.

**Comment by theLordz** [comment]
@sheeep Thank you too.
![config](https://cloud.githubusercontent.com/assets/15924018/17623468/dc626678-60a8-11e6-9366-9176e634cb6e.jpg)
![trace](https://cloud.githubusercontent.com/assets/15924018/17623469/dc65590a-60a8-11e6-9218-f88523d051b8.jpg)

**Comment by theLordz** [comment]
Reporting that console command bin/console oneup:uploader:clear-chunks throws same exception.

**Comment by snarktooth** [comment]
I believe this is a duplicate of #255.

**Comment by theLordz** [comment]
Hello @snarktooth! Thanks for your reply.
It's not that user scenario and it's not related to the OrphanageStorage class.

_In short the problems is this:_
**$this->handleChunkedUpload($file, $response, $request) when we try to configure chunks storage using flysystem.**

The scenario is so:
**1.** We have a js uploader that splits big files in small chunks.
**2.** We extend AbstractChunkedController and send these chunks via $this->handleChunkedUpload($file, $response, $request).
**3.** Rest of the process via event listeners.

Basically we try to upload all the chunks directly on sftp via flysystem. Then when the uploaderBundle tries to get that list of chunks in order to reassemble the input original file throws that exception.

Right now we use the chunks uploading on local filesystem and the mapping same way. We have the upload servers different from the api ones so we just have to manage a new way in distributing the post processes using api as local video provider.


Because the mapping itself with the storage type as flysystem is ok and working well, we can upload the big file on sftp using only the mapping. But this way we loose efficiency, because the client js uploader knows how to handle some network problems or resume after a failover. Not mentioning double tasks for one file: uploading in chunks, assembling locally and then reupload the big file on video server via sftp.

**Comment by snarktooth** [comment]
You're right; the problems with the Flysystem chunk handling are more extensive than just the attempt to use listFiles.  It looks like the Uploader\Chunk\FlysystemStorage class was copied verbatim from the Gaufrette equivalent without being fully adapted to account for Flysystem's differences.
