### ISSUE TITLE
Notice: A non well formed numeric value encountered [with solution]

### ISSUE THREAD

**Issue by chriskonnertz** [1up-lab/OneupUploaderBundle#277]
Hello,

there is a little incompatibility with PHP 7.1.

In PHP 7.1 this notice occurs:
"A non well formed numeric value encountered" (in `Oneup\UploaderBundle\DependencyInjection\OneupUploaderExtension.php` in line 265, 266 or 267.

The code that is responsible for this notice:
```
            case 'g': $input *= 1024;
            case 'm': $input *= 1024;
            case 'k': $input *= 1024;
```

`$input`then is something like this: `2M` so it is a string. Before PHP 7.1 it was not a problem to multiply a string with an int, but in PHP 7.1 a notice is shown.

Example code to demonstrate that problem:
```
$value = '2M';
$value *= $value * 1024;
```
You can run this code here: http://sandbox.onlinephpfunctions.com/ Run it with PHP 7.1 and for example 7.0.1 to see the difference.

Solution:
You have to properly case the string to an int before the multiplication happens. A simple `(int) $input` should do the work. Another proposal: `filter_var($input, FILTER_SANITIZE_NUMBER_INT);`

**Comment by bytehead** [comment]
Hello

Which version are you using? In `1.7.5` the issue shouldn't exist anymore (see #275).

**Comment by chriskonnertz** [comment]
Oh, thank you. Also thanks for the fast reaction!

**Comment by bytehead** [comment]
You're welcome :)
