### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by tousignantf** [1up-lab/OneupUploaderBundle#279]
Please update your doc for the listeners:
 - { name: kernel.event_listener, event: oneup_uploader.post_upload**.gallery**, method: onUpload }

should be written instead of :

 - { name: kernel.event_listener, event: oneup_uploader.post_upload, method: onUpload }

After following your very basic documentation, I had to find this piece of information here:
http://stackoverflow.com/questions/38295832/symfony-3-1-and-oneupuploaderbundle-blueimp-uploadlistener-is-not-called

Also, the provided example with fineUploader is not working, we get stuck with JS errors. I had to fallback to BlueImp/Jquery, but the doc for sending custom data seems to focus on fineUploader, which is quite annoying.

However, thanks for the bundle. Except for the documentation, it's good.

**Comment by Myystigri** [comment]
It's written in the doc. The basic example tell you that there's more specifics informations about event [here](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/events.md) and on this page it's written.
