### ISSUE TITLE
pass variable to Custom Namer

### ISSUE THREAD

**Issue by doxt3r** [1up-lab/OneupUploaderBundle#283]
Hi all,
I'm trying to use a customr namer, i want to pass à variable from my form to be used to create a folder.
Full description is here:
https://stackoverflow.com/questions/46026198/custom-namer-oneuploadbundle-symfony

Thank you

**Comment by kingdom96** [comment]
I have the same problem

**Comment by doxt3r** [comment]
I set a variable in the session that I destroy once I used it, I don't think it is the right way to do so :0
In the [documentation](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_logic.md), it is described how we perform this by extending request and adding a param,
but Cna't see how I can use this variable with my custom Namer ;/

**Comment by kingdom96** [comment]
"sorry for my english",
i'm fix them [doc](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_logic.md)
i'am pass my var in my javascript script, i'am using jqurry file upload 
`
 $('#fileupload').fileupload({
            maxChunkSize: 1000000 ,
            add: function (e, data)
            {
                var that = this;
                $.post('{{ oneup_uploader_endpoint('gallery') }}', {file: data.files[0].name}, function (result) {
                    var file = result.file;
                    data.uploadedBytes = file && file.size;
                    data.formData = {reference : {{ reference.getId() }}};

//....
`
