### ISSUE TITLE
Add method for deleting orphanage contents / Reset

### ISSUE THREAD

**Issue by tlorens** [1up-lab/OneupUploaderBundle#288]
I think this has been asked before, but when a user chooses to upload a file to an **Item1**  and then changes their mind and selects another **Item2**, the previously uploaded file is still in the orphanage and calling `->getFiles()` fetches the files meant for **Item1**.   I can't find a `delete` method and I can easily write my own to do this.

**Comment by bytehead** [comment]
Did you try the `clear()` method in the [OrphanageManager](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Uploader/Orphanage/OrphanageManager.php#L30)?

**Comment by tlorens** [comment]
`clear` seems to take into consideration `maxage` from the config.  I did see a `cleanup` function in there though.

**Comment by tlorens** [comment]
Secondly, if a user uploads multiple files (they've changed their mind or uploaded the wrong one) I'll need to clean things out before the new file is uploaded.  Trying to think where that would go, I can't exactly put that in an of the `Pre` events.

**Comment by bytehead** [comment]
Did you have a look at #251 and #88?

**Comment by tlorens** [comment]
Thanks, reading those posts got me thinking.  I just finished up prototyping the uploader and so far so good.. Thanks again for the nudge in the right direction.

**Comment by bytehead** [comment]
No worries, you're welcome 👍
