### ISSUE TITLE
Is there a way to upload a file(files) through controller?

### ISSUE THREAD

**Issue by zloyboldin** [1up-lab/OneupUploaderBundle#291]
Can i use this bundle to upload files, got in POST API parameters, using configs and listeners created to handle frontend upload?
Everything is fine when i upload file from sonata admin, but how can i do it from controller?

**Comment by bytehead** [comment]
You can even use a custom uploader: https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_uploader.md

**Comment by zloyboldin** [comment]
@bytehead yes, i saw this, but a can't understand how to use it...
Could you provide a simpliest example?

When i upload file from front i use fineuploader, i think he does all the job, but what should i do if i send image file in POST parameter? 
How can i upload it to s3 server (prod) or in local folder (dev)?

**Comment by bytehead** [comment]
Maybe this https://github.com/1up-lab/OneupUploaderBundle/issues/98 helps?
I've never used S3 so far, I can't help you there.

**Comment by zloyboldin** [comment]
@bytehead in this file 
/vendor/oneup/uploader-bundle/Oneup/UploaderBundle/Controller/UploadifyController.php

we have a function $this->handleUpload($file, $response, $request);
all the job is done by it, is there any way to make the same functionality from another controller?

**Comment by bytehead** [comment]
I don't get your point. You can customize any upload logic with a custom eventlistener with custom logic as explained in https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_logic.md.
Otherwise write your own Controller and overwrite the config for the corresponding uploader.

**Comment by zloyboldin** [comment]
@bytehead I don't use qq.FineUploader, i just use api method, where file passed as POST parameter. So not any of these listeners are fired. 
I just want file to get stored in the same directory, as if i used my qq.FineUploader(...) way!

**Comment by bytehead** [comment]
Hmm, maybe @sheeep can give any advice?

**Comment by zloyboldin** [comment]
@bytehead 
For the future, if somebody would be interested in this there is a way to use same configurations, as for the JS upload

In services file:
```
app.media_library.file_manager:
      lazy: true
      class: AppBundle\Services\MediaLibrary\FileManager
      arguments: ["@oneup_flysystem.media_image_fs_filesystem", "@oneup_uploader.storage.media"]

```

In FileManager class:
```
    /**
     * @var Filesystem
     */
    private $filesystem;

    /**
     * @var FlysystemStorage
     */
    private $storage;

    /**
     * FileManager constructor.
     * @param Filesystem $filesystem
     * @param FlysystemStorage $storage
     */
    public function __construct(Filesystem $filesystem, FlysystemStorage $storage)
    {
        $this->filesystem = $filesystem;
        $this->storage = $storage;
    }

    /**
     * @param File $file
     * @return Media|null
     */
    public function upload(File $file)
    {
        try {
            $filesystemFile = new FilesystemFile($file);
            $filename = uniqid() . '.' . $filesystemFile->getExtension();
            $result = $this->storage->upload($filesystemFile, $filename);

            $media = new Media();
            $media->setTitle($filesystemFile->getClientOriginalName());
            $media->setFile($filename);

            return $media;
        } catch (\Exception $exception) {
            return null;
        }
    }
```

And finally in controller:
```
$file = $request->files->get('image');
$media = $this->get('app.media_library.file_manager')->upload($file);
```

**Comment by bytehead** [comment]
Thanks for investigation! I'll reference to this for future questions!
