### ISSUE TITLE
Is this bundle compatible (or when will be?) with Symfony 4?

### ISSUE THREAD

**Issue by Lifeformwp** [1up-lab/OneupUploaderBundle#297]
Hello, when I trying to install this bundle on my 4.0.0-RC1 composer gives me error that v3.4 is minimum-stability. Will you support ^4 and when? Or am I doing something wrong?

**Comment by bytehead** [comment]
There is a PR #295, but the tests do still fail and it's not yet complete. But the goal is to support `^4.0`

**Comment by Lifeformwp** [comment]
Thank you!

**Comment by klodoma** [comment]
Any timeline when you will release the support for Symfony4? 
As I see it's already developed in a branch. Thx.

**Comment by bytehead** [comment]
@Lifeformwp @klodoma 
There's a [release/2.0.0](https://github.com/1up-lab/OneupUploaderBundle/tree/release/2.0.0)-branch - could you test and give feedback if possible?

**Comment by klodoma** [comment]
@bytehead I will give it a try the next days as we plan to upgrade to Symfony4. I'll provide my feedback.

**Comment by bytehead** [comment]
Thank you, I'll await your feedback!

**Comment by klodoma** [comment]
Hi, so my current feedback... , I am aborting the upgrade of our project to 4. There are too many dependencies in the project that are currently failing the upgrade. 

Still, if I'll find some spare time I'll give it a shot and test your bundle on Symfony4.

**Comment by soifou** [comment]
@bytehead I'm testing your release/2.0.0 branch and no problem to report so far 👍 

I only had to create package and routing files in `config/`. You plan to create a contrib recipe for it, right?

**Comment by ErnadoO** [comment]
Hello @bytehead

i'm testing release/2.0.0 too and i found one thing.

Like in your documentation, I use Orphanage like this:
`$manager = $this->get('oneup_uploader.orphanage_manager')->get('products');`

But Sf4 don't like it:

> The "oneup_uploader.orphanage.products" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

I had fix it, i will send a PR soon ;)

**Comment by francoispluchino** [comment]
@bytehead For me, it's ok, but the PR #311 must be merged. When will the 2.0 version be released in stable?

**Comment by bytehead** [comment]
@soifou Thanks for your feedback!
It is planned, but I don't know, when I have time for it. Wanna create a PR? 🙂 

@francoispluchino #311 is merged. I think we should also provide a contrib receipe before release the stable 2.0.

**Comment by soifou** [comment]
@bytehead PR done, waiting for 2.0 version to be released :)

**Comment by bytehead** [comment]
Thank you! I'll release 2.0 asap!

**Comment by bytehead** [comment]
[Version 2.0.0](https://github.com/1up-lab/OneupUploaderBundle/releases/tag/2.0.0) is out! 
Thanks to everyone involved! 🎉
