### ISSUE TITLE
symfony #24993 breaks the uploader bundle

### ISSUE THREAD

**Issue by dominikzogg** [1up-lab/OneupUploaderBundle#298]
I seems that the newest symfony bugfix releases (>2.7) breaks the bundle https://github.com/symfony/symfony/pull/24993

**Comment by dominikzogg** [comment]
seems to be fixes in 1.9, but 1.9 seems to be a bc cause sf bc...

**Comment by bytehead** [comment]
We do not implement the changed [`RequestHandlerInterface`](https://github.com/symfony/symfony/pull/24993/files#diff-9db319ade116fe83563d1a5ad84e6b2aR7).

**Comment by dominikzogg** [comment]
@bytehead downgrading symfony and oneupUploader solves the problem, working with 1.9 leads in a signature change, could be a symfony independ one

**Comment by bytehead** [comment]
> working with 1.9 leads in a signature change

Only in Symfony, not in our bundle.

**Comment by dominikzogg** [comment]
1) ...TypeError: Argument 2 passed to Oneup\UploaderBundle\Event\ValidationEvent::__construct() must implement interface Oneup\UploaderBundle\Uploader\Response\ResponseInterface, instance of Symfony\Component\HttpFoundation\Request given...

**Comment by dominikzogg** [comment]
Downgrade to 1.7.x solves the problem

**Comment by bytehead** [comment]
Ok, but that' s not an issue related to this.

**Comment by bytehead** [comment]
It's related to #294

**Comment by dominikzogg** [comment]
@bytehead did you missed its a BC?

**Comment by bytehead** [comment]
Seems like. I remember that I thought about it while reviewing #294. It will be fixed with #299 in `1.9.1`.

**Comment by bytehead** [comment]
Thanks for reporting!

**Comment by dominikzogg** [comment]
@bytehead your welcome
