### ISSUE TITLE
Make a redirect on onUpload

### ISSUE THREAD

**Issue by ockang** [1up-lab/OneupUploaderBundle#301]
Hello community, how are you? it is possible that when you upload an image you can achieve a redirect? I'm trying several methods and it does not work, my idea is when onUpload finishes the cycle of the image send a redirect.

**Comment by bytehead** [comment]
Hi @ockang 
You can customize your logic with a custom `EventListener` and you could return a `RedirectResponse` in the `onUpload` method of your listener. See more [here](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_logic.md).
