### ISSUE TITLE
rb+ broke my uploading to ASW (with Guzzle)

### ISSUE THREAD

**Issue by mydoctool** [1up-lab/OneupUploaderBundle#303]
Uploader/Storage/FlysystemStorage.php

line 41 $stream = fopen($file->getPathname(), 'rb+');

in vendor/guzzlehttp/psr7/src/Stream.php

if (!$this->readable) {
throw new \RuntimeException('Cannot read from non-readable stream');
}

in Guzzle:

private static $readWriteHash = [
'read' => [
'r' => true, 'w+' => true, 'r+' => true, 'x+' => true, 'c+' => true,
'rb' => true, 'w+b' => true, 'r+b' => true, 'x+b' => true,
'c+b' => true, 'rt' => true, 'w+t' => true, 'r+t' => true,
'x+t' => true, 'c+t' => true, 'a+' => true
],
'write' => [
'w' => true, 'w+' => true, 'rw' => true, 'r+' => true, 'x+' => true,
'c+' => true, 'wb' => true, 'w+b' => true, 'r+b' => true,
'x+b' => true, 'c+b' => true, 'w+t' => true, 'r+t' => true,
'x+t' => true, 'c+t' => true, 'a' => true, 'a+' => true
]
];

**Comment by Lctrs** [comment]
@mydoctool Can you test my PR #304 and tell me how it's working for you ?
