### ISSUE TITLE
Can't access login & registration page after composer update oneup

### ISSUE THREAD

**Issue by ghiyati** [1up-lab/OneupUploaderBundle#309]
Hello, i got this error on /login & /register 

Attempted to load class "AbstractController" from namespace "Symfony\Bundle\FrameworkBundle\Controller".
Did you forget a "use" statement for "Oneup\UploaderBundle\Controller\AbstractController"?

in vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php at line 29   -
 * @author Christophe Coevoet <stof@notk.org>
 */
class SecurityController extends AbstractController
{
    /**
     * @var CsrfTokenManagerInterface
     */

Any help please ?

**Comment by bytehead** [comment]
That error is related to https://github.com/FriendsOfSymfony/FOSUserBundle/.
