### ISSUE TITLE
Bug BlueimpController

### ISSUE THREAD

**Issue by cltobim** [1up-lab/OneupUploaderBundle#316]
Hello,

I found a problem with the method parseChunkedRequest line 71 : 
` $last = ($endByte + 1) === $totalBytes;`

I fix the problem with a cast :
`$last = ($endByte + 1) === (int)$totalBytes;`

**Comment by bytehead** [comment]
Thank you! I'll fix it asap!

**Comment by cltobim** [comment]
No problem

**Comment by bytehead** [comment]
Version `2.0.1` is released. Thank you for reporting!
