### ISSUE TITLE
Change status code of response

### ISSUE THREAD

**Issue by nicolaspetitjean** [1up-lab/OneupUploaderBundle#317]
Hello

I look for for a way to change status code of response. I'm using an event listener which have to return an `EmptyResponse`, but not way to change the status code (in my case, i'd like to return 201 instead of 200, because i create a new entity after the upload.
Regards !

**Comment by bytehead** [comment]
If you get the `Response` object in your event listener you can just change the status code returned: 
```php
$response = $event->getResponse();
$response->setStatusCode(Response::HTTP_CREATED);
$event->setResponse($response);
```

**Comment by nicolaspetitjean** [comment]
Well, i thought about that, but those two methods doesn't exist in `EmptyResponse`. Maybe i'm wrong, but when you do `$response = $event->getResponse();` you get an `EmptyResponse`, not a `Response`.

**Comment by bytehead** [comment]
I see. There's no simple way to do it :smirk: 
You could try to register your custom controller to overwrite the `upload()` method.
@sheeep any thoughts on this?

**Comment by sheeep** [comment]
@nicolaspetitjean Can you tell me what kind of uploader you're using?

This is indeed not easily solvable, as the development of the `Response`-part was - in hindsight - not my brightest moment. I assume the easiest solution is to just create a custom controller.

**Comment by nicolaspetitjean** [comment]
@sheeep i'm using dropzone. I think `EmptyRespponse` should extends Symfony's `Response` ?

**Comment by nicolaspetitjean** [comment]
Looks like i'm the only one who have such ideas [#71](https://github.com/1up-lab/OneupUploaderBundle/issues/71)
