### ISSUE TITLE
Event Listener (On Upload)

### ISSUE THREAD

**Issue by glanes** [1up-lab/OneupUploaderBundle#321]
Hey peeps,

This is not actually a issue or a problem, but can't find anywhere else the answer
Is it possible each uploader object has their own event listener (onUpload)?
I have declared both on services, but it is only going to the first one.

    app.rpl_evidence_listener:
        class: AppBundle\EventListener\RplEvidenceListener
        arguments:  ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

    app.credit_evidence_listener:
        class: AppBundle\EventListener\CreditEvidenceListener
        arguments:  ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }

Cheers

**Comment by bytehead** [comment]
Hi there

What is the output of `php bin/console debug:event-dispatcher oneup_uploader.post_persist`?

**Comment by glanes** [comment]
Hey,
this is what i got

**Registered Listeners for "oneup_uploader.post_persist" Event
============================================================

 ------- ------------------------------------------------------------ ---------- 
  Order   Callable                                                     Priority  
 ------- ------------------------------------------------------------ ---------- 
  #1      AppBundle\EventListener\RplEvidenceListener::onUpload()      0         
  #2      AppBundle\EventListener\CreditEvidenceListener::onUpload()   0         
 ------- ------------------------------------------------------------ ---------- 
**

**Comment by sheeep** [comment]
So, your  `CreditEvidenceListener` is not called? Looks good to me, actually.
