### ISSUE TITLE
Blueimp Overload the translation file

### ISSUE THREAD

**Issue by itokia** [1up-lab/OneupUploaderBundle#325]
Hello,
I wish to overload the translation file in order to put the error messages in french.
How can I do it please.
Thank you

**Comment by bytehead** [comment]
Just put it under `app/Resources/translations/OneupUploaderBundle.fr.yml`, should be loaded then.

**Comment by itokia** [comment]
Thank for your reponse but it's not work.

My config.yml

`#ONEUPLOADER uploader de fichier
oneup_uploader:
    mappings:
        gallery:
            frontend: blueimp #dropzone # or any uploader you use in the frontend
            #error_handler: oneup_uploader.error_handler.blueimp
            max_size: 10M
            allowed_mimetypes:
                - 'image/jpeg'
                - 'image/png'
                - 'text/plain'
                - 'application/pdf'
                - 'application/vnd.oasis.opendocument.text'
                - 'application/vnd.oasis.opendocument.spreadsheet'
                - 'application/vnd.oasis.opendocument.presentation'
                - 'application/vnd.ms-powerpoint'
                - 'application/msword'
                - 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'`

And the file for translation in app/Resources/translations/OneupUploaderBundle.fr.yml
`error:
    maxsize: Ce fichier est trop volumineux.
    whitelist: Le type de fichier n'est pas supporté.
    blacklist: Le type de fichier n'est pas autorisé.`

**Comment by bytehead** [comment]
Sorry, wrong path. Should be `app/Resources/OneupUploaderBundle/translations/OneupUploaderBundle.fr.yml`.

**Comment by itokia** [comment]
Must the file be declared somewhere?
It always shows me on the screen  'error.whitelist'

**Comment by itokia** [comment]
sorry, I forgot to declare  translator: ~ in my config.yml
