### ISSUE TITLE
Can i somehow extend GaufretteStorage and inject my storage to plugin

### ISSUE THREAD

**Issue by n1ks2n** [1up-lab/OneupUploaderBundle#326]
I need to extend some functionality on top of GaufretteStorage, for example generating url to file by it's name on server. It makes sense to add this to Storage cause Storage has access to actual config and should know where the application stores files. So my question is that why Storages aren't configures like services cause there is no possibilities to inject overriden service and also to use this service in some custom helpers. And if i miss something and there is the way to do it please give me an example.

**Comment by bytehead** [comment]
Hi there!
I'm not sure, if I understand you correctly. The storages are actually registered as services: https://github.com/1up-lab/OneupUploaderBundle/blob/a2f48b71a5cd3c4e4b75bff364dfb588660ab8f9/DependencyInjection/OneupUploaderExtension.php#L191

Why don't you extend `GaufretteStorage` and replace this? https://github.com/1up-lab/OneupUploaderBundle/blob/a2f48b71a5cd3c4e4b75bff364dfb588660ab8f9/Resources/config/uploader.xml#L14

**Comment by n1ks2n** [comment]
Trying to extend the service and replace parameter using compilerPass makes no effect. And also service should be registered as a service not a param, to be able to override it in compiler pass.

**Comment by bytehead** [comment]
I see. Seems to be a wrong decision back in the days. Did you check any possibilities when [using Flysystem as storage layer](https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/flysystem_storage.md)?

**Comment by n1ks2n** [comment]
This is the same as Gaufrette storage layer. I mean the difference between those two abstractions is only under the hood. And as u can check in bundle config - Flysystem is also set up as parameter. And tbh Gaufrette is used be default in my project and there is no way to change it now. But i've managed to do what i've needed in different way just using base Gaufrette Bundle functionality. So u can close this question now, just wanted maintainers to know that there are some lacks in architecture that prevent this bundle to be extended and easier implemented to projects =))

**Comment by bytehead** [comment]
I totally understand your point of view. We are aware of this lacks (same here https://github.com/1up-lab/OneupUploaderBundle/issues/317), we just don't have time to improve this atm 🙂
Thanks anyway for mention it, we take care of this in the next major!
