### ISSUE TITLE
dinamic upload folder

### ISSUE THREAD

**Issue by ikerib** [1up-lab/OneupUploaderBundle#333]
Hi,
I'm developing and extranet and I'm using Finder & Filesystem components to do that. The fact is that I need to upload n documents to the current folder...
I checked this bundle but in the config section, you set the folder where the files are going to be uploaded...

is there any way to change it dinamically? In my case to the Finder current folder...
thanx in advance

**Comment by jonasarts** [comment]
I successfully use a custom namer to change folders dynamically for uploaded files.
https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_namer.md

On the last example, I just inject some more directories like:

```
public function name(FileInterface $file)
{
    return sprintf('%s/%s/%s',
            'folder1',
            'subfolder1',
            'myfilename.dat'
        );
}
```

Dependency Inject your Finder, get the current folder and use that?


On an other project, I used just the `post_persist` event and moved the files to some final destination as I liked:
https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_logic.md
