### ISSUE TITLE
Deprecations since Symfony 4.1

### ISSUE THREAD

**Issue by robertfausk** [1up-lab/OneupUploaderBundle#334]
```Passing a size as 4th argument to the constructor of "Symfony\Component\HttpFoundation\File\UploadedFile" is deprecated since Symfony 4.1.```

It's used in 
https://github.com/1up-lab/OneupUploaderBundle/blob/a2f48b71a5cd3c4e4b75bff364dfb588660ab8f9/Uploader/File/FilesystemFile.php#L13
https://github.com/1up-lab/OneupUploaderBundle/blob/a2f48b71a5cd3c4e4b75bff364dfb588660ab8f9/Uploader/File/FilesystemFile.php#L15
https://github.com/1up-lab/OneupUploaderBundle/blob/a2f48b71a5cd3c4e4b75bff364dfb588660ab8f9/Uploader/Chunk/Storage/FilesystemStorage.php#L92
https://github.com/1up-lab/OneupUploaderBundle/blob/a2f48b71a5cd3c4e4b75bff364dfb588660ab8f9/Controller/MooUploadController.php#L114
and in their tests.

I think we need to check for symfony/http-foundation>=4.1 when creating instances of UploadedFile.
What do you think?

**Comment by robertfausk** [comment]
One year later :smiley_cat:  Any news on this?

**Comment by bytehead** [comment]
Not yet 🙁 Would you like to provide a pull request?

**Comment by TiGR** [comment]
The problem with this is that Symfony does not provide clean way to avoid this. There are no new contracts or interfaces, the only way to avoid this is to either use reflection or somehow detect currently used symfony version number.

Which brings us to the question if we are using `UploadedFile` wrong. Generally speaking, this is really dirty and hackish way to use `UploadedFile`. All the usages in this library do that in "test mode" (passing `true` as the last constructor argument).

So, as I see it, we should not rely on using code in "test mode" at all, and solution here should be not avoiding deprecation notice, but avoiding test mode.

**Comment by robertfausk** [comment]
Close this in favor of #373
