### ISSUE TITLE
Configuration Info for max_size is wrong

### ISSUE THREAD

**Issue by mablae** [1up-lab/OneupUploaderBundle#338]
It says: 

```
            ->scalarNode('max_size')
                                ->defaultValue(\PHP_INT_MAX)
                                ->info('Set max_size to -1 for gracefully downgrade this number to the systems max upload size.')
```
But when you look at the code, -1 is never replaced by ini values or anything. Everything bigger that -1 would be just rejected. Since we have no access to `\PHP_INT_MAX` in yaml and xml this should probably be reworded to: 

"Without the max_size option defined, it will gracyfully downgrade to internal php max-upload sizes"

**Comment by bytehead** [comment]
It is fixed in the newest release (`2.0.4`), see #329.

**Comment by mablae** [comment]
@bytehead Thanks for the pointer. And thanks for the work on this bundle!

**Comment by bytehead** [comment]
You're welcome, thanks for the kudos!
