### ISSUE TITLE
Custom namer for chunk upload directory

### ISSUE THREAD

**Issue by jonasarts** [1up-lab/OneupUploaderBundle#343]
I use successful a custom namer to put uploaded files in some deeper nested folders.

uploader/<sessionid>/<some_business_logic>/file.extension

Now I'd like to use the same nesting on the chunk upload directory. Can I somehow enable/use a namer also for the chunk directory name / file name? Or is there any other possibility to influence the chunk directory dynamically?

Like
cache/<sessionid>/<some_business_logic>/0_chunk...

Currently the uploader generates
cache/<sessionid>/0_chunks...

**Comment by bytehead** [comment]
I don't think so. And why do you want to change a path in the cache directory?

**Comment by jonasarts** [comment]
I want to cleanup some sensitive data immediately after upload. This works nice with the custom namer subfolder. It would be easy to just remove the same folder from the chunks dir.
But I found out, that the uploader generates unique directories, even if I run multiple concurrent uploads (in multiple browser tabs).
For now I just store the unique chunks directory name and remove it along with the target subfolder. (If it still exists, after an aborted upload.) Works ok.
