### ISSUE TITLE
Event for if image is deleted

### ISSUE THREAD

**Issue by xeon826** [1up-lab/OneupUploaderBundle#346]
I'm using Dropzone as my frontend and have enabled the option to delete uploaded images, I'm wondering if there's an event I could use for this and if not if there's a way I could create one?

**Comment by heiybb** [comment]
```
class UploadListener
{
    public function onUpload(PostPersistEvent $event): ResponseInterface
    {
        $file = $event->getFile();
        $response = $event->getResponse();
        $files = array();
        $files[] = array(
            'success'=>true,
            'file_link' => '/uploads/gallery/' . basename($file),
        );
        $response['files'] = $files;
        return $response;
    }
}
```

You can try to implement your own listener to return a delete url in the response.
Then for the delete url action, you need to create another function to handle that in your controller.
