### ISSUE TITLE
Software requirements

### ISSUE THREAD

**Issue by tcdaly** [1up-lab/OneupUploaderBundle#349]
Please clarify which versions of the software require which versions of PHP?  Do later versions require PHP7?

**Comment by tcdaly** [comment]
Thank you.  Are you sure, because I am finding return type declarations in the code of version 1.8.3, which I believe is a feature only compatible with PHP 7?

**Comment by bytehead** [comment]
That's true. Where are this return type declarations? We removed the PHP 5.x tests in 1.8.3, so it could be the case.

**Comment by tcdaly** [comment]
I'm getting a PHP parse error in 'Oneup/UploaderBundle/DependencyInjection/Compiler/ControllerPass.ph
  p' on line 10 - but I think that file may be dynamically generated by Symfony?

**Comment by bytehead** [comment]
If you have this file (and this error), you'll have the 2.x version installed.

**Comment by tcdaly** [comment]
I've currently got v1.8.3 installed, but I installed the git source code because I'm hoping to make an amendment to the code.

**Comment by bytehead** [comment]
1.8.3 has no `ControllerPass`.

**Comment by tcdaly** [comment]
Thanks.  Not sure how that happened, but reinstalled 1.8.2 and problem has gone away.
