### ISSUE TITLE
Custom uploader - How to get the symfony translator

### ISSUE THREAD

**Issue by Falseee** [1up-lab/OneupUploaderBundle#353]
I use a custom upload (like https://github.com/1up-lab/OneupUploaderBundle/blob/master/Resources/doc/custom_uploader.md), the problem is i dont know how i can inject/get the symfony translator in the upload function.

**Comment by bytehead** [comment]
You can get the translator from the container in your controller: 
```php
$translator = $this->container->get('translator');
```
