### ISSUE TITLE
Symfony 3.4 & Symfony 4 documentation (and updates)

### ISSUE THREAD

**Issue by DavidGarciaCat** [1up-lab/OneupUploaderBundle#360]
Hey there,

Although the Bundle works on the latest versions of Symfony, the documentation doesn't seem to be up to date. It might cause confusion for those less-experienced developers that are trying to learn Symfony and use this Bundle at the same time.

Please consider updating the documentation to include the required changes for the autowire and other (minor) changes due to the new settings. Please bear in mind that the service to handle the custom namer forces the developer to use public services too.

Cheers,

**Comment by divined** [comment]
Yep, how can install it on Symfony 4 (

**Comment by FBL-dev** [comment]
Up ? :(
