### ISSUE TITLE
Symfony 4.3 deprecations 

### ISSUE THREAD

**Issue by KDederichs** [1up-lab/OneupUploaderBundle#361]
Since 4.3 calling the dispatcher with the event name as first parameter is deprecated:
`
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as first argument is deprecated since Symfony 4.3, pass it second and provide the event object first instead.
`

At first glance I found that one in the AbstractController

**Comment by bytehead** [comment]
Fixed by #362.
