### ISSUE TITLE
Chunks and NFS v3 file locking issue

### ISSUE THREAD

**Issue by doxt3r** [1up-lab/OneupUploaderBundle#381]
Hello,

I have an issue on reassembling the chunks stored on an NFS mounted filesystem. It seems that NFS v3 does not support file locking:

`[2020-07-23 17:47:32] request.CRITICAL: Uncaught PHP Exception RuntimeException: "Reassembling chunks failed." at /var/www/mine/app/vendor/oneup/uploader-bundle/Uploader/Chunk/Storage/FilesystemStorage.php line 71 {"exception":"[object] (RuntimeException(code: 0): Reassembling chunks failed. at /var/www/mine/app/vendor/oneup/uploader-bundle/Uploader/Chunk/Storage/FilesystemStorage.php:71)"} []`

Is there any workaround for this ?

Thank you

**Comment by bytehead** [comment]
Which version of the UploaderBundle do you use?

**Comment by doxt3r** [comment]
@bytehead :        "oneup/uploader-bundle": "^2.0",

**Comment by bytehead** [comment]
Did you try version 3.x as well?

**Comment by doxt3r** [comment]
Upgraded system to nfs v4, it worked, sorry for the delay to close the issue.

**Comment by bytehead** [comment]
Thank you for the feedback! Glad it works 😎
