### ISSUE TITLE
Orphanage with Symfony 5

### ISSUE THREAD

**Issue by AntoineTesson** [1up-lab/OneupUploaderBundle#388]
Hello,

I'm reworking a project. In SF 3.4 no problem, but with Symfony 5.1 i have still the error : 
Service "oneup_uploader.orphanage_manager" not found: even though it exists in the app's container

I have declared like this : ` $em2 = $this->get ( 'oneup_uploader.orphanage_manager' )->get ( 'pjcommande' );`

Hummmm orphanage is OK with SF 5 ? And if yes, how to use now ? 
Best regards

**Comment by bytehead** [comment]
Hi there

Do you have it configured properly like in https://github.com/1up-lab/OneupUploaderBundle/blob/master/doc/orphanage.md#using-the-orphanage? 

Can you paste your mapping config?

**Comment by AntoineTesson** [comment]
Hello =) This is my configuration 

package/oneup_uploader.yaml
`oneup_uploader:
    orphanage:
        maxage: 1200
        directory: '%kernel.cache_dir%/public/uploader/orphanage'
    mappings:
        messagerie:
            frontend: dropzone # or any uploader you use in the frontend
            use_orphanage: true
        annexe:
            frontend: dropzone # or any uploader you use in the frontend
            use_orphanage: true
        pjcommande:
            frontend: dropzone # or any uploader you use in the frontend
            use_orphanage: true
        documentclient:
            frontend: dropzone # or any uploader you use in the frontend
            use_orphanage: true    `

**Comment by bytehead** [comment]
What does `php bin/console debug:container oneup_uploader.orphanage_manager` output?

**Comment by bytehead** [comment]
I think I know, where your problem is :)
Since Symfony 4.4 all services are private by default. You can't get this service from the container anymore.
You should use dependency injection instead.

**Comment by bytehead** [comment]
If you add this to your `config/services.yaml`:
```yaml
Oneup\UploaderBundle\Uploader\Orphanage\OrphanageManager: '@oneup_uploader.orphanage_manager'
```
you should be able to inject the autowired service:
```php
class DemoController
{
    private OrphanageManager $orphanageManager;

    public function __construct(OrphanageManager $orphanageManager)
    {
        $this->orphanageManager = $orphanageManager;
    }

    /**
    * @Route("/")
    */
    public function index(): Response
    {
		$om = $this->orphanageManager->get('pjcommande');
		// ...

		return new Response();
	}
}
```
