### ISSUE TITLE
ResponseInterface should implement \ArrayAccess

### ISSUE THREAD

**Issue by ndench** [1up-lab/OneupUploaderBundle#389]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0

#### Summary

According to [the documentation](https://github.com/1up-lab/OneupUploaderBundle/blob/4e79231a74e40d2d3fe24bb78fa360e640138753/doc/custom_logic.md#process-uploaded-files-using-custom-logic), you can process uploaded files using custom logic and pass update the Response using array access to pass extra data through:

```php
// ...

class UploadListener
{
    // ...
    
    public function onUpload(PostPersistEvent $event)
    {
        //...
        
        //if everything went fine
        $response = $event->getResponse();
        $response['success'] = true;
        return $response;
    }
}
```

The issue here is:
* `$event->getResponse()` [returns ResponseInterface](https://github.com/1up-lab/OneupUploaderBundle/blob/4e79231a74e40d2d3fe24bb78fa360e640138753/src/Event/PostUploadEvent.php#L73)
* [ResponseInterface](https://github.com/1up-lab/OneupUploaderBundle/blob/4e79231a74e40d2d3fe24bb78fa360e640138753/src/Uploader/Response/ResponseInterface.php) does not implement `\ArrayAccess`
* So at "compile time" (eg. static analysis with phpstan/psalm/your IDE), we receive an error with this approach.
* It works at runtime, but only because all implementations of `ResponseInterface` extend [AbstractResponse](https://github.com/1up-lab/OneupUploaderBundle/blob/4e79231a74e40d2d3fe24bb78fa360e640138753/src/Uploader/Response/AbstractResponse.php), which implements `\ArrayAccess`

#### How to reproduce

1. Create an UploadListener as described in the documentation
2. Use some form of static analysis, eg. [psalm](https://github.com/vimeo/psalm/), [phpstan](https://github.com/phpstan/phpstan), or you IDE of choice.
3. Notice the reported error

PhpStan:
![image](https://user-images.githubusercontent.com/2062388/100811364-35ee3e00-3486-11eb-8cb2-95c30cbff9a0.png)

Psalm:
![image](https://user-images.githubusercontent.com/2062388/100811506-82397e00-3486-11eb-8398-6d68cb9c1855.png)

PhpStorm with EA Extended plugin:
![image](https://user-images.githubusercontent.com/2062388/100811553-9e3d1f80-3486-11eb-8be8-2b15597e38de.png)

#### Suggested fix

Move the `implements \ArrayAccess` declaration from `AbstractResponse` to `ResponseInterface`. 

Happy to send through a PR for this, just want to validate that there isn't something I'm missing.

**Comment by bytehead** [comment]
Hey @ndench

Thanks for the issue! Seems totally legit and reasonable to me.
IMHO is altering an interface a BC break though, isn't it?

**Comment by ndench** [comment]
@bytehead that's a good point about BC. We should be able to use `@implements` in phpdoc to be compatible. Then switch it to a proper implements in the next major version.

**Comment by ndench** [comment]
Unfortunately, `@implements` and `@extends` didn't work. But I have created a PR for the next major version.

**Comment by bytehead** [comment]
Closing this in favor of #392 and #391.
