### ISSUE TITLE
Response in the EventListener, problem with generated url:  \/ instead of /

### ISSUE THREAD

**Issue by eric72** [1up-lab/OneupUploaderBundle#390]
### Question

|    Q        |   A
|------------ | ------
| Version 2.0     | x.y.z

Hi,
I've followed the documentation, and when i try to add field 'url' in my response, it return me an url like that: url\/someurl instead of url/someurl.
Instead of / i got \ / , but if i dump this, i got the right url with \ / instead of this \/.
It only happen in the return of the response array..
I don't understand why.

**Comment by eric72** [comment]
Since i return a plain/text instead of a json, plain/text should change this character / by \/, but how can i change my response to be a JsonResponse then ?

**Comment by bytehead** [comment]
See #394
