### ISSUE TITLE
How can i change my response type in my listener to json instead of plain/text ?

### ISSUE THREAD

**Issue by eric72** [1up-lab/OneupUploaderBundle#394]
### Question

|    Q        |   A
|------------ | ------
| Version     | x.y.z

Hi,

In my listener i would like to return a json instead of a plain/text.
This is what i did: 
`$response = $event->getResponse();
 $response['url'] = 'route/myUrl'
`
Where can i change the type return to be json ? It keep to be plain/text.
Thanks in advance for your help

**Comment by bytehead** [comment]
What about `$response->headers->set('Content-Type', 'application/json');`?

See also: https://symfony.com/doc/4.4/components/http_foundation.html#creating-a-json-response

**Comment by eric72** [comment]
I've already tested this at the beginning, but it doesn't worked.
I guess the bundle return a response after your listener call.
You can only change the state of getResponse();

I've made a post on stackoverflow too, where i answered myself, here : https://stackoverflow.com/questions/65179631/symfony-oneup-uploader-bundle-problem-wenth-generating-url-in-response-sepa/65183746#65183746

**Comment by bytehead** [comment]
How does your listener look like?

**Comment by eric72** [comment]
`
public function onPostUpload(PostUploadEvent $event) {

        $response = $event->getResponse();
        try{
            $response['name'] = "filename.txt";
            $response['uploaded_file_path'] = $file->getPath();
            $response['url'] = 'route.xyz/myRoute'
            $response->headers->set('Content-Type', 'application/json');
        } catch (\Exception $error) {
            return $response['error'] = $error;
        }

}
`

It return me a json if i use my  dropzone, it return me a plain/text if i test with an http client.

**Comment by bytehead** [comment]
Probably because Dropzone is sending a header `Accept: application/json` and the application returns with the same.

**Comment by eric72** [comment]
But even with dropzone, i got the same problem, it return me a plain/text with \ / instead of / ..

**Comment by eric72** [comment]
Can you please reopen my issue ? Or do i have to open a new one ?

**Comment by eric72** [comment]
yeah, i just added: "Accept: application/json" on my http client and worked perfectly, thanks

**Comment by bytehead** [comment]
👍 nice. You're welcome!
