### ISSUE TITLE
Symfony 5.3: RequestStack::getMasterRequest() is deprecated, use getMainRequest() instead

### ISSUE THREAD

**Issue by keksa** [1up-lab/OneupUploaderBundle#407]
Hello, just reporting a deprecation notice, that bubbled up from our tests.

```
Since symfony/http-foundation 5.3: "Symfony\Component\HttpFoundation\RequestStack::getMasterRequest()" is deprecated, use "getMainRequest()" instead.
```

https://github.com/1up-lab/OneupUploaderBundle/blob/3d711a21d4a983443797b83bd763557067e72b85/src/Controller/AbstractController.php#L229

**Comment by keksa** [comment]
Found another one, sessions as a service are deprecated too:
https://github.com/1up-lab/OneupUploaderBundle/blob/3d711a21d4a983443797b83bd763557067e72b85/src/Controller/AbstractController.php#L69

https://symfony.com/blog/new-in-symfony-5-3-session-service-deprecation

**Comment by bytehead** [comment]
Thank you!

**Comment by keksa** [comment]
I'm not sure what's the best way of keeping BC with Symfony <= 5.2, if you can advise I'd be happy to send a PR.

**Comment by bytehead** [comment]
Closing in favor of #408
