### ISSUE TITLE
Problem filename with final file after cunked

### ISSUE THREAD

**Issue by Jasonlgrd** [1up-lab/OneupUploaderBundle#411]
Hello,

I have problem with gaufrette file chunked. After upload last chunk and Gaufrette rename file, new key isn't accessible. New key is in fileSystem->fileRegister but fileRegister is protected. How is possible i can access in final key in event oneup_uploader.post_upload.gallery ?

![Capture d’écran 2021-11-03 à 09 03 16](https://user-images.githubusercontent.com/35960493/140026197-0ea3da57-a3dc-4f62-b086-9a921d551bf5.png)

Thank you so much

**Comment by bytehead** [comment]
Hi @Jasonlgrd 

I'm not sure if I can help you here. Did you check all written stuff over [here](https://github.com/1up-lab/OneupUploaderBundle/blob/master/doc/chunked_uploads.md)?

**Comment by Jasonlgrd** [comment]
Hi @bytehead 

My problem concern probably Gauffrette bundle ! 

Thank

**Comment by bytehead** [comment]
Thanks for feedback!
