### ISSUE TITLE
Config Object for Interaction with uploaded Files in Services

### ISSUE THREAD

**Issue by Hanmac** [1up-lab/OneupUploaderBundle#414]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | yes/no

#### Scenario

My current scenario is that i'm in a Service that got a relative path for a uploaded image from an Entity.
Now to get the absolute path for the file to read i would need to get the uploads directory somehow for the correct gallery.

i could try to inject the needed one_up parameters into my Service myself but that could be way to complex

#### Summary

have some Config Object that can be passed to Services, maybe even make it autowire using parameter name?

so when using `$gallery->getPath($relativePath)` would return the absolute path
and configurations like root_directory and other default values will be already handled

**Comment by bytehead** [comment]
Injecting the parameter sounds totally correct to me and is IMO not complex. It is possible to autowire parameters: https://symfony.com/doc/current/service_container.html#binding-arguments-by-name-or-type

**Comment by Hanmac** [comment]
i mean i could try to inject the config settings for a oneup subsection, but then i still would have to take care about all the default parameters stuff, like for example if the directory in the storage isn't defined or if root_directory is used, i still would have problems with that. (especially for the other storage systems)

if such config service would have been managed by the Bundle, especially if the if the Config Service automatically knows the right config just by parameters like `Config $gallery`

would it be ok if i try to make an MR for this over the holidays?

**Comment by bytehead** [comment]
Pull requests are always welcome and the are a better base to discuss features on code examples ❤️

**Comment by Hanmac** [comment]
@bytehead short question that is somehow related to the Config idea:

what is the best/preferred way to get the file (stream) back from a once uploaded file?

for example, i get the following parameters: the id of the uploader (for example gallery) and the file name after it got passed the namer.
now i want to read that file, like getting the new absolute path, or when its passed through other systems like the Flysystem, getting a FileStream to read?

or is returning the uploaded file outside of this bundle?
