### ISSUE TITLE
Getting the old filename in pastUpload after namer

### ISSUE THREAD

**Issue by Hanmac** [1up-lab/OneupUploaderBundle#415]
### Question

|    Q        |   A
|------------ | ------
| Version     | 3.1.3

I don't know if its more a Feature Request than a Bug or just a general Question:

My Customers are only allowed to upload special file names from a list. (Database Entries)
so i have a Subscriber for `validation` and `pastUpload`
in validation i check if the uploaded file name is in the list of allowed names.

in pastUpload i mark the file in the list as uploaded. (setting filesystem path and other properties)

in the Validation Event i still have the old name of the uploading file,
but this information is missing in the pastUpload when the file only has the name given by the namer. (the file on the file system should still be a cryptic one)

What would be the best way to handle such a problem? my current one is to add attributes to the Request object?

**Comment by bytehead** [comment]
Did you check the original request for occurences on the original filename? Adding attributes is one possibility. You could also think of a seperate service (which you inject) tracking the filename changes during the request?
