### ISSUE TITLE
PHP 8.1 compatibility / deprecation warnings

### ISSUE THREAD

**Issue by Knallcharge** [1up-lab/OneupUploaderBundle#422]
### Bug Report

After updating to PHP 8.1 the following deprecation warnings are issued:
PHP Deprecated:  Return type of Oneup\UploaderBundle\Uploader\Response\AbstractResponse::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor\oneup\uploader-bundle\src\Uploader\Response\AbstractResponse.php on line 49
.
Deprecated: Return type of Oneup\UploaderBundle\Uploader\Response\AbstractResponse::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor\oneup\uploader-bundle\src\Uploader\Response\AbstractResponse.php on line 49

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.3

#### Summary

PHP 8.1 deprecation warnings

#### How to reproduce

Use the bundle with PHP 8.1

**Comment by bytehead** [comment]
Fixed by #427
