### ISSUE TITLE
Hi There, is there any plans to upgrade the bundle to symfony 7? I have upgrade my project however oneup is not working.

### ISSUE THREAD

**Issue by glanes** [1up-lab/OneupUploaderBundle#442]
### Question

|    Q        |   A
|------------ | ------
| Version     | x.y.z

**Comment by bytehead** [comment]
Is already in the main branch (`dev-main`). Tag should follow soon.

**Comment by bytehead** [comment]
[5.0.0](https://github.com/1up-lab/OneupUploaderBundle/releases/tag/5.0.0) is out 🥳
