### ISSUE TITLE
Make the getFiles method of OrphanageStorage public

### ISSUE THREAD

**Issue by sudent** [1up-lab/OneupUploaderBundle#48]
Hello, nice bundle!

In regards to using orphanage will upload all the file from previous visits, can we just use the getFiles() method from the service (oneup_uploader.orphanage.{mapping}) and decides what to do with the existing files instead? 

Eg. I can get the files uploaded (if any) when the user did upload some files previously. And its up to own implementation to either redisplayed the files in template/remove it from within the controller.

The issue with this is I see getFiles method is protected. Any advice on this? Thanks

**Comment by benglass** [comment]
We are using getFiles and typehinting on OrphanStorageInterface, wondering if there is a reason why getFiles isnt part of OrphanStorageInterface, seems like it should be. Just to avoid BC?
