### ISSUE TITLE
Use two upload zones

### ISSUE THREAD

**Issue by mj-bdl** [1up-lab/OneupUploaderBundle#59]
Hi, I am using this bundle with Dropzone. What I am wondering now is how to use two:
- one to upload only images and 
- another one to upload only documentation (doc, pdf, ...).

How can I handle this?

Thanks in advance.

**Comment by armilleiwilliam** [comment]
I followed the instructions above but I have the following error:
'An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "_uploader_upload_documents" as such route does not exist.")'

This is my code:
oneup_uploader:
    mappings:
        documents:
            frontend: blueimp
            namer: acme_demo.custom_namer
        gallery:
            frontend: blueimp
            allowed_mimetypes: ["image/gif", "image/jpeg", "image/png"]

In the routing.yml is the following:
oneup_uploader:
    resource: .
    type: uploader

In my twig:
{{ oneup_uploader_endpoint('documents') }}

I tried also to substitute "documents" with "images" but it seems it takes only "gallery". Any idea?

**Comment by armilleiwilliam** [comment]
Ok, I've found the solution. I had to clear the cache, even if it seems weird to me, maybe because when symfony2 imports the config.yml into config_dev.yml it retrieves the copy from the cache instead of the original copy just modified. The bundle is very good ;-)
