### ISSUE TITLE
Chunk uploading and load balancing - how is it supposed to work

### ISSUE THREAD

**Issue by eXtreme** [1up-lab/OneupUploaderBundle#72]
Hi, I'm prepping my webapp for horizontal scaling (from 1 server to 3+) and I was really happy to see info about chunked upload behind load balancers in changelog in version 1.0. But the more I look at the code and test on my local env I can't understand how it is supposed to work.

You introduced gaufrette as a storage so I thought I would be able to store chunks on S3, but the only storage supported is local storage because "The filesystem used as chunk storage must implement StreamFactory". So how is it different from previous approach since we use local stream storage for chunks? 

So with 3MB file with 1 MB chunks they will be sent: 1st to Server#1, 2nd to Server#2 and 3rd to Server#3 - how can Server#3 assemble the file when all chunks are distributed to other servers? And how to send the file later to S3 when moving a file from stream to stream loads the whole file into memory (with bigger upload I can run out of memory for PHP).

**Comment by sela** [comment]
@eXtreme have you implemented the chunks upload to S3?  I got similar issue as you.

**Comment by eXtreme** [comment]
@sela it was a long time ago :) As far as I remember I used some jquery uploading library to upload the file directly to S3 using S3 Multipart Upload (with progress bar and so on) and some custom backend code to handle moving that file to a destination bucket; without acutally using this bundle. I can't help more, I don't have the access to the code.

**Comment by sela** [comment]
Thanks for the help @eXtreme I assume you use POST signed url then. That's my plan B if the first one doesn't go well.
